### ISSUE TITLE
Neutral creature changes its sprite before hero appears nearby using "Dimension Door" spell

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1142]
When you use "Dimension Door" spell to teleport hero to the neutral creature, Creature changes to attacking state before hero appears nearby. 
I think, neutrals should change its sprite after hero was completely drawn after spell.
Note that creatures attack hero in this case only when "only the first monster will attack(H2 bug)" option is switched off.
![Attacking creature](https://user-images.githubusercontent.com/55348946/88480636-bb556500-cf5f-11ea-926c-b79ddbc6798d.jpg)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

The "world: only the first monster will attack (H2 bug)." option is bugged. (https://github.com/ihhub/fheroes2/issues/1272)

Also the behavior of the creatures when a hero teleports near a wandering troop with the Dimension Door spell has been corrected to work as in the original game. (https://github.com/ihhub/fheroes2/pull/2350)

So the creature sprite should no longer change its state when this option is disabled.
Note: Currently only the sprite is changed, the wandering troop does not attack the hero, which is normal.

**Comment by Branikolog** [comment]
@LeHerosInconnu 
It seems to me, that recently creatures didn't attack hero out of Dimension Door, while option was turned on, and attacked, while switching off the option you mention above.
Anyway, as we're heading to original gameplay, we need to make the game working properly and even take away this option for some time, as I cannot tell anymone what and how should it change.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

In the original game, in the example, only one wandering troop attacks the hero.
In fheroes2, the "world: only the first monster will attack (H2 bug)." option must be enabled to work as in the original game, otherwise both troops attack.

That's why I think fheroes2 is buggy and this "option" is a fix.

In the original game:

![Attack adjacent troop H2 01](https://user-images.githubusercontent.com/43583994/105641005-ff2f1580-5e81-11eb-96ff-4bc9b86e1417.png)
