### ISSUE TITLE
World map shouldn't have an ability to be scrolled while hero moves

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1159]
Currently, player can scroll world map, after hero started moving.

**Comment by ihhub** [comment]
Hi @Branikolog , how is it a bug?

**Comment by Branikolog** [comment]
Hello. 
While hero is moving, we can scroll the screen to any side, but when we stop - screen jumps back to hero. That causes very strange and confusing screen behaviour, if player accidently points screen edges with his mouse... 
In my opinion, screen should always be focused in a hero, while he moves.

**Comment by Branikolog** [comment]
Anyway, in the OG cursor disappears at all, while hero is moving. So player cannot move screen/

**Comment by LeHerosInconnu** [comment]
It is true that this is a problem that does not occur in the original game because the mouse cursor is not displayed and is not active.

In fheroes2, the hero was heading towards the Daemon Cave when I moved the cursor to the lower edge of the game screen causing the window to display inconsistently.

Non-standard display:

![Daemon Cave fh2 move cursor 01](https://user-images.githubusercontent.com/43583994/91603462-52ea1100-e96d-11ea-8700-1f53002fbf88.png)

Standard display:

![Daemon Cave fh2 move cursor 02](https://user-images.githubusercontent.com/43583994/91603478-5aa9b580-e96d-11ea-8287-5ce8836411a2.png)
