### ISSUE TITLE
Graphic fault of the pressed button "Battle Only"

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1225]
When pressed, the "Battle Only" button has graphical flaws.

![Graphic fault of the pressed button Battle Only 01](https://user-images.githubusercontent.com/43583994/90286895-0edc1400-de77-11ea-8fea-31b1379d01e3.png)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , all graphic issues we're trying to fix in the new game engine which will be soon ready for initial testing.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

It is really good that you have chosen to develop a new graphics engine, it will greatly benefit the project with all the shadows issues on the adventure map, etc.
Looking forward to the next version of the project.
Good continuation.
I will stop reporting issues related to shadows and graphics, thanks for the info.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , no-no. Please don't stop. This is an issue not related to new engine as I found right now.

New engine targets to fix rendering problems while missing shadows or this button representation are issues of generating an image using the engine.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

Okay I see.
Wouldn't it be better to wait for the release of this new engine to report these types of errors, I don't really want to do the same job over dozens of times.
Will there be an intermediate version before the official 0.9 version?

**Comment by idshibanov** [comment]
> Wouldn't it be better to wait for the release of this new engine to report these types of errors, I don't really want to do the same job over dozens of times.
> Will there be an intermediate version before the official 0.9 version?

@LeHerosInconnu In my opinion it is better to wait for engine update before reporting graphical glitches. Nobody wants to do double work. It will be also helpful in case we miss something during the update, because engine integration process is a very manual task.

We're still debating if it's worth making another official release before 0.9. Ideally you could compile master branch to get the latest builds in the future. The process isn't difficult to set up and can be done using free and available tools. We also distribute occasional test builds among ourselves. Things like that easier to coordinate in [Discord](https://discord.gg/xF85vbZ), that's why we created our own server there.

**Comment by LeHerosInconnu** [comment]
Hello @idshibanov.

Yes that's what I thought, I'll focus on the other types of bugs for now.

Regarding the last builds, I'm not a programmer, and I don't necessarily have the time or the inclination to install new programs, and that's also without counting the time needed for compilation, etc.

I don't know if it is possible to automatically generate the latest version of fheroes2 on Github.
The latest version would therefore always be available for download and ready to use, even if it is not the last "official version".
It would be a bit like how the "Nightly builds" work for the OpenXcom project, always up to date with the latest code.

And it's also a bit too bad that when a team member compiles a version it is not available, forcing all team members to compile the same version too, it's a bit of a time lost to do the same thing.
