### ISSUE TITLE
Hero's default creatures

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#1265]
In fheroes2, at the start of the scenario, it happens that the hero has only gargoyles in his army.
In the original game, this never happens.
In the original game, either the hero has one level 1 troop and one level 2 troop, or the hero has one level 1 troop only, but never has one level 2 troop only.

![Hero's default creatures 01](https://user-images.githubusercontent.com/43583994/90415626-a9279c00-e0b1-11ea-8e61-6338e3d0bbf5.png)

**Comment by idshibanov** [comment]
In OG (original game) there's a hardcoded table of all unit combinations. AI can actually buy a hero with level 3 unit if you didn't know (about 30% chance).

**Comment by LeHerosInconnu** [comment]
Hello @idshibanov,

I did not know that.
Is this valid for all levels of difficulty?

**Comment by idshibanov** [comment]
> I did not know that.
> Is this valid for all levels of difficulty?

Yes, for every difficulty, could be 1-2 (or 2-3 for pikeman) level 3 units in the starting army. It is hard to notice because AI often buys units right after hero purchase anyway. There's actually a lot of small bonuses for AI in original game, based both on difficulty and personality. 

For example chance of negative morale event in battle is lower than for player. Another example is explorer AI heroes that gain a small boost to mobility (and more likely to buy more heroes).

Speaking of this issue, I'm planning to fix it in the near future (that's why moved to 0.9), but after we will finish with big feature work, like ongoing engine integration.

**Comment by LeHerosInconnu** [comment]
Hello @idshibanov,

Yes, I knew AI had slightly higher benefits, for triggering both positive and negative morale and luck, and also that the AI had bonuses depending on the personality of the AI.
If that can make the game more fun, I don't mind the AI cheating a bit.
The AI already starts with a big handicap when playing against a human player.

The new engine must be a "big chunk", good motivation for that.

**Comment by Branikolog** [comment]
To my mind, all small AI cheats can be turned on for higher difficulty levels.
