### ISSUE TITLE
Animation for Mage shooting is incorrect

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#149]
Currently the animation is used from different creature. Here is how it shows now (notice small fireball):
![image](https://user-images.githubusercontent.com/19829520/66306791-2bddb780-e935-11e9-8340-9105a26b8b99.png)

and here how it should be:
![image](https://user-images.githubusercontent.com/19829520/66306901-795a2480-e935-11e9-9e74-21970bd7520a.png)

**Comment by taeber** [comment]
I tracked down in [battle_troop.cpp/Battle::Unit::ICNMiss()](https://github.com/ihhub/fheroes2/blob/c11ec2e18a6975e8303ca51409ee456af6c76ec3/src/fheroes2/battle/battle_troop.cpp#L2003-L2006) where the Druid's "missle" is being selected for both the Mage and Archmage's missle. I didn't see a `MAGEMSL` (nor anything else obviously belonging to the Mage) in the ICN list, so I'm not sure how to fix this.

According to the SVN history though, it looks like it has been this way since the code was [added](https://github.com/taeber/fheroes2/blob/6d5e9136866f0f2836fb2e2db207841a07557a47/fheroes2/src/fheroes2/battle2/battle_stats.cpp#L1691-L1692).

**Comment by idshibanov** [comment]
There is no graphics or projectile data for mages, only a beam starting point offset and shooting time (765ms). I believe this is simply drawn as a line on top of everything else.

**Comment by ihhub** [comment]
You're right, @idshibanov , it's just a straight line with 2 colors:
![image](https://user-images.githubusercontent.com/19829520/81473500-80317880-9231-11ea-8279-6df299dd463e.png)
![image](https://user-images.githubusercontent.com/19829520/81473517-8f182b00-9231-11ea-96a8-f3c8e491b24b.png)

**Comment by idshibanov** [comment]
@ihhub  Yes, I actually looked at the drawing call for this, but it's very convoluted to understand. Basically luck, lighting and mage bolt is drawn using the same function. What I also know that it's animated with 10ms updates.

Shooting time is for the mage animation to lower down his staff.

**Comment by ihhub** [comment]
The start point of the animation (or line) we know from bin file. We could do something similar for now, no need to be an exact cooy from the original game.

**Comment by idshibanov** [comment]
@ihhub we need a function that would draw line with set thickness. What approach would work best for both SDL1 and SDL2? I only thought of either going pixel level (same as current `DrawLine`) or rotating a texture (but this is SDL2 only?).

**Comment by ihhub** [comment]
Hi @idshibanov we need to create a function with same pixel by pixel drawing. It should pretty easy to implement.
