### ISSUE TITLE
Neutral creatures change its type on a world map

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1859]
We can see some trolls on a screenshot.
![image](https://user-images.githubusercontent.com/55348946/94820032-a76b2b00-0408-11eb-9f99-b19984ea2bd5.png)
When we collect treasure chest, suddenly, they change into peasants!
![image](https://user-images.githubusercontent.com/55348946/94820417-1d6f9200-0409-11eb-8119-b404e49ded83.png)
When we attack we see nobody.)
![image](https://user-images.githubusercontent.com/55348946/94820487-30826200-0409-11eb-83ce-58df2ea0c0e4.png)
The end...
![image](https://user-images.githubusercontent.com/55348946/94820644-5f003d00-0409-11eb-9e57-9c1f62fd2bcc.png)

**Comment by ihhub** [comment]
Hi @Branikolog , could you please provide a save for this? I assume it's related to @idshibanov changes recently.

**Comment by idshibanov** [comment]
Yes, I definitely needed a save here, on a fresh scenario load everything is alright. What happened here is that "trolls" did spawn during one of the monster weeks, they are not there at the start. Game didn't set up the monsters correctly, that's why there's "peasants" on the map. Have to fix monster placement code.

Automatic battle surrender is another bug here, battle shouldn't even start if army is invalid.
