### ISSUE TITLE
Mouse click during movement in battle causes auto movement of next creature

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#208]
Start a battle and move your monster to any position. During it's movement click on another hexagon and notice that if next creature to move is able to reach this position it will move immediately after getting it's movement.

**Comment by oleg-derevenetz** [comment]
It seems that this bug is no longer reproducible.

**Comment by Branikolog** [comment]
Indeed!
Bug is gone! :D

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz and @Branikolog,

It was not a bug but a feature (quality of life). :D Really. :)

It allows to program a sequence of actions in advance, without waiting for the end of the animation.
This is not perfect in Heroes 2 because there is a certain timing to respect in the way of programming the actions (making clicks in sequence).
This could have been improved in fheroes2 in order to program the actions without precise timing.

In addition, another feature could also be added in fheroes2 with the possibility to undo an action (or several actions) during the combat.

In original game:

https://user-images.githubusercontent.com/43583994/110202890-a7fe6680-7e6b-11eb-96da-a75a80c21389.mp4

https://user-images.githubusercontent.com/43583994/110202907-b5b3ec00-7e6b-11eb-89cf-70f46241db63.mp4

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Well, actually this "feature" was always a headache for me: I often misclick while trying to enter log or simply made 1 unwanted click which causes the next creature fly towards the place I left cursor...
So, now it works not so fast, but predictable and without any surprising aftermath.
Also, if you want to play battle faster, we have a wide variety of speed adjustments in options, which helps in setting the maximum comfortable speed.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu
> Well, actually this "feature" was always a headache for me: I often misclick while trying to enter log or simply made 1 unwanted click which causes the next creature fly towards the place I left cursor...

That's why I think a "Undo" feature (for several actions not just the last one) during the combat would be welcome.

> So, now it works not so fast, but predictable and without any surprising aftermath.

I've seen let's play where this ability to program movements in advance is considered a good feature. :)

> Also, if you want to play battle faster, we have a wide variety of speed adjustments in options, which helps in setting the maximum comfortable speed.

This is not only related to the speed of the animations.
The player may want a medium speed animation with the possibility to program actions, and it is not necessarily all the time that he wants to program actions.

**Comment by Branikolog** [comment]
@LeHerosInconnu 
You can consider me as conservative and stubborn growler, but such "programming" is too complicated for me. I prefer the game be predictable and simple in this way. :D
Let's assume, that the majority of people playing this game are not so keen heroic-leaders, as you or me. :)
Anyway, everything is debatable.
