### ISSUE TITLE
No sounds for Windows SDL 1 version

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#210]
If you run Windows version of the game with SDL 1 support you would notice that there are no sounds but music only. It should be related to SDL 1 but we are not sure yet about it.

**Comment by andrey-starodubtsev** [comment]
Besides suggested PR there're two more issues:

1. I experienced "no sound" situation on my VM with Windows... But right after that it requested to restart to install pending updates, and I failed to reproduce this issue after restart.
If you still do not hear sound for SDL1 builds (after applying changes from this PR), please let me know.

2. There're differences between vanilla game and `fheroes2` in settings screen besides those already fixed:

- different texts for settings button ("music" instead of "Music", "off" instead of "Off" etc.)
- Music/Sound volume are getting quieter instead of louder when user click on the button
- When Music/Sound has zero volume, sprite for the button is changed in the original game. `fheroes2` uses changed sprite when Music/Sound are turned off using `fheroes2.cfg`.

Should we address this issues? Should it be done here, in this PR or separately?

**Comment by ihhub** [comment]
Second issue must be addressed in a separate PR for sure as it's related to GUI component mostly.

**Comment by ihhub** [comment]
@andrey-starodubtsev I see that you partially addressed second issue in your PR, didn't you?
