### ISSUE TITLE
Hero cannot disembark at areas without coast object

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2128]
At the screenshot hero can't create a path to disembark on some area of the beach. 
![image](https://user-images.githubusercontent.com/55348946/97560706-1cbe2180-19f0-11eb-80a9-b2c8654688fd.png)
![image](https://user-images.githubusercontent.com/55348946/97560740-26478980-19f0-11eb-9caa-17f7b5fd29e3.png)
![image](https://user-images.githubusercontent.com/55348946/97560765-2d6e9780-19f0-11eb-9743-451ff1032f21.png)

**Comment by LeHerosInconnu** [comment]
@Branikolog.

The hero cannot disembark because there is an object in this square at the beginning of the scenario (resource stack, wandering creatures, treasure chest, event, artifact, etc.).

When the object has been removed, the square is not marked as free.
The hero should also be able to land on a square where an event is located and trigger it.

This bug is also present in the original game.
There is a scenario to test this here: https://heroes2.forumactif.com/t851-heroes-2-bugs-blocked-disembarkment.

![Blocked disembarkment fh2 01](https://user-images.githubusercontent.com/43583994/97716186-9c68f080-1ac3-11eb-87a1-4a71b5cd2458.png)

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Thanks for your precision! 
Now this bug will be fixed easier! :)

**Comment by idshibanov** [comment]
Hey @LeHerosInconnu @Branikolog 

In Heroes 2 there's a hidden object called OBJ_COAST, it is placed on empty tiles when map is saved in the map editor. It is easy to see which object is set on a tile when right-clicking on ground in game (you'll see "Coast" in the popup). At this moment we follow the same logic to be compatible with the original.

As a partial solution we could place those "coast" objects when pickup object is removed.

**Comment by LeHerosInconnu** [comment]
Hi @idshibanov,

Thank you for the explanations.

There is also a problem when the top of the sprite of a castle is close to the place where the hero wants to land although there is no object in this square at the beginning of the scenario.

In original game:

![Unable to land 02](https://user-images.githubusercontent.com/43583994/97804060-b8989900-1c4d-11eb-835a-700a76753214.png)

In fheroes2:

![Unable to land fh2 01](https://user-images.githubusercontent.com/43583994/97804062-be8e7a00-1c4d-11eb-840a-02e809c29294.png)

There are scenarios to test this here: https://heroes2.forumactif.com/t854-heroes-2-bugs-unable-to-land.
