### ISSUE TITLE
Campaign bonuses

### ISSUE THREAD

**Issue by shprotru** [ihhub/fheroes2#2382]
The goal of this ticket is make working campaign's completeness and bonus choosing.
To my understanding, what need to do make campaign bonuses choosing right, I decide to collect and organize some information on campaigns. Pay attention on bonuses: how they are different and how much of them. Need to collect information about campaigns in similar form.
Additionally, pay attention, for future purposes, on winning and losing conditions: how they are different and how much of them. No need to make them work for this ticket, this is just for notice.

[RolandCampaign.xml](https://github.com/ihhub/fheroes2/files/5705428/RolandCampaign.txt)
[PriceOfLoyalty.xml](https://github.com/ihhub/fheroes2/files/5705392/PoL.txt)

**Comment by LeHerosInconnu** [comment]
**Spoilers alert.
Read no further if you wish to discover the Heroes 2 campaigns without revelation.** ;)

Hello @shprotru,

There are some flaws in your file. :)
(Github does not display the tags.)

- With the type for the "Thunder Mace" artifact:
(Also, I don't know if "Loose" with two "o" instead of "Lose" is intentional in the term "LooseAllTowns" and other terms containing "Loose".)

<Type>LooseAllTowns</Type>
<Artifact>Thunder Mace</Artifact>

- With "Lord Halton" and "Wyrm" in "Defender":
The hero "Lord Halton" is controlled by the player playing on Roland's side, the hero "Wyrm" is an opponent on Archibald's side.
https://mightandmagic.fandom.com/wiki/Wyrm_(Necromancer)
https://www.youtube.com/watch?v=621PhQhFYO4&list=PLJ0FzIR2zrGTPLhZfnBDfuNgSdBC11gM-&index=18

<Name>Defender</Name>
<Hero>Lord Halton Wyrm</Hero>

- With "Lord Halton" and "Wyrm" in "The Gauntlet":
The heroes "Lord Halton" and "Wyrm" are not present in this scenario.
https://www.youtube.com/watch?v=d0nj3DyGJ-s&list=PLJ0FzIR2zrGTPLhZfnBDfuNgSdBC11gM-&index=19

<Name>The Gauntlet</Name>
<Hero>Lord Halton Wyrm</Hero>

- With "Noraston", "a" instead of "o", "Naraston" instead of "Noraston":

<Description>Lose Noraston</Description>
<LooseTown>Naraston</LooseTown>

- "Betrayal" scenario is missing:
https://mightandmagic.fandom.com/wiki/Betrayal_(Roland)
https://www.youtube.com/watch?v=NNcnNy_FiDc&list=PLJ0FzIR2zrGTPLhZfnBDfuNgSdBC11gM-&index=17

Roland campaign:
https://mightandmagic.fandom.com/wiki/Roland%27s_campaign

Look in the playlist for all campaigns:
https://www.youtube.com/watch?v=UIS5dz4w0-I&list=PLJ0FzIR2zrGTPLhZfnBDfuNgSdBC11gM-

**Comment by shprotru** [comment]
Hi @LeHerosInconnu! I making correctives for Roland's campaign, there is "Noraston", instead of "Naraston" in code of `fheroes2`, and on [fandomwiki](https://mightandmagic.fandom.com/wiki/Defender_(H2)). This is mainly technical information, to understand direction in which project should move: what is done, and what should be done. This information provides us with ready-to-made data structures for campaigns: how they should look like, which different options we should support, to make it compatible with OG.

**Comment by LeHerosInconnu** [comment]
Hello @shprotru,

> Hi @LeHerosInconnu! I making correctives for Roland's campaign(updated first post), there is "Noraston", instead of "Naraston" in code of `fheroes2`, and on [fandomwiki](https://mightandmagic.fandom.com/wiki/Defender_(H2)). For Betrayal will be updated later. This is mainly technical information, to understand direction in which project should move: what is done, and what should be done. This information provides us with ready-to-made data structures for campaigns: how they should look like, which different options we should support, to make it compatible with OG.

Okay. :)

There is also another bonus in Roland and Archibald's campaigns.

"Sister Eliza appears as a recruitable hero in the player's castle starting from the 7th scenario as a reward for the completion of the Defender scenario (number 6 in the Roland's campaign of Heroes II)."

https://mightandmagic.fandom.com/wiki/Eliza

"Brother Brax appears as a recruitable hero in the player's castle starting from the 5th scenario as a reward for the completion of the "Necromancers" scenario (number 3 in the Archibald's campaign of Heroes II)."

https://mightandmagic.fandom.com/wiki/Brax

**Comment by vincent-grosbois** [comment]
For award list : https://gamefaqs.gamespot.com/pc/932491-heroes-of-might-and-magic-ii-gold/faqs/77670/campaign-awards-guide
