### ISSUE TITLE
Optimize struct VecCastles

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#2385]
`struct VecCastles` is based on `std::vector`. This struct is used for Interface::Radar calling Get method. The complexity of this method is O(N) which is very slow. We need to optimize this struct and instead of std::vector use std::map to reduce search complexity to O(log(N)).

To observe how much time this method eats try to profile a situations of fast switching between heroes:
![image](https://user-images.githubusercontent.com/19829520/102039844-fc162380-3e05-11eb-9081-eb8e7f3286b1.png)

Even this method takes **2%** of the time it's still very slow for such a tiny function.

**Comment by vincent-grosbois** [comment]
Is the time taken in this method really due to time complexity of VecCastles::Get() though?

For the radar we call in a loop all map positions so VecCastles::Get is called already a lot of times (ie for each tile where a castle sprite appears)

The check is then in O(n) but should be in itself quite fast imo, seeing that we have a most 75 castles

If we put instead a Map or Hashmap, we have to put in this container all the locations of the castle sprite, so that is 8 times more times. Then the look-up is asymptotically faster but I'm not sure the real total time will be smaller

Another possibility is to store the castle color in the tile object so it can be directly accessed

**Comment by vincent-grosbois** [comment]
Here's one way to fix it : https://github.com/ihhub/fheroes2/pull/2476
