### ISSUE TITLE
Add Polish font

### ISSUE THREAD

**Issue by J013k** [ihhub/fheroes2#2453]
Hello.

A dev who made fork for Vita [(fheroes2-vita)](https://github.com/Northfear/fheroes2-vita) directed me here...
To ask for help upstream devs.

Is there a way to add Polish font?
I mean letters like `Ą ą Ć ć Ę ę Ł ł Ń ń Ó ó Ś ś Ź ź Ż ż`.

I have missing signs or strange artifacts: 
![https://i.postimg.cc/br8SPGZC/New-game.jpg](https://i.postimg.cc/br8SPGZC/New-game.jpg)
![https://i.postimg.cc/0yrfF3R6/Start.jpg](https://i.postimg.cc/0yrfF3R6/Start.jpg)

I also have a problem with translation.
Some things are in Polish, some in English:
![https://i.postimg.cc/L847XNdR/PL-ENG.jpg](https://i.postimg.cc/L847XNdR/PL-ENG.jpg)

**Comment by ihhub** [comment]
Hi @J013k currently we do not properly support any languages except English. This will be added after 0.9 release. The problem with font support is an absence of unicode fonts in the era of HoMM2 so the original game assets contain only one language (or a mix of two). However, we have a potential way to do this but sadly localization is not the main priority right now so please be little patient about this.

**Comment by ihhub** [comment]
Hi @J013k , I think we can make a small hack to make Polish language work. Since the above letters are very similar to the original English alphabet we can use certain English characters instead of special ones in Polish. Of course it's not an ideal solution but it'd be better than missing characters after all.

**Comment by ihhub** [comment]
@J013k also since you own a Polish version of the game could you please investigate one thing related to Polish language support in the original game? It's needed to add few lines of the code and compile on your machine and then tell use the result.
We can't ask you to share game resources and it's illegal :)

**Comment by J013k** [comment]
@ihhub do you have any public e-mail?
Or account at any of these forums PSX-Place, obscuregamers?

**Comment by J013k** [comment]
Unfortunately I do not have an environment to compile anything...
I'm a simple noob. ;)

I can only add that I have a Windows version of this game:
![https://i.postimg.cc/vBLQV2KH/her2.png](https://i.postimg.cc/vBLQV2KH/her2.png)

**Comment by ihhub** [comment]
Hi @J013k , it's okay. Thanks! We'll try to find a developer who owns non-English version of the game to start with.

**Comment by J013k** [comment]
Is there any chance for a test version (Windows SDL x64)?

**Comment by ihhub** [comment]
Hi @J013k , you can download the latest compiled version from [GitHub Releases](https://github.com/ihhub/fheroes2/releases), mostly second page of it.
