### ISSUE TITLE
Using cmake as build system?

### ISSUE THREAD

**Issue by winterheart** [ihhub/fheroes2#2480]
Hello.

I've noticed that fheroes2 uses bare Makefiles as buildsystem. While this approach has advantages as simple and fast solution, it has may become more and more complex solution, which can be difficult to maintain and extend.

I can offer my help to add CMake support that can ease and facilitate project. Pros of CMake is:
* Support for variety of platforms and toolchains
* Extendable and easy configuration
* Wide support from IDEs (Visual Studio, Clion, XCode etc)
* Wide support for system's build environment (can produce project files for Make, Ninja, XCode etc)

**Comment by ihhub** [comment]
Hi @winterheart , we could add cmake support as an alternative build system, not as a replacement of makefile. Cmake has many drawbacks such as extra piece of software to be installed and weird VS project files compilation.
You could make a pull request for this.

**Comment by dimag0g** [comment]
@winterheart it would be interesting to see the results, however, as someone who ported a bunch of old games to a bunch of platforms, I came to the conclusion that such advanced build systems rarely improve things in practice. Common platforms don't need them because all the common libs and include files are there, as well as tools to discover them such as `pkg-config`. On more exotic platforms, advanced build systems try to guess which compiler/linker arguments to use, which is good in theory. Problem is,  they often guess wrong, and then I have to figure a way to circumvent the autodetection and force the right settings. So in the end it's the same amount of time spent (if not more) compared to a plain Makefile.

Now, I'm not against CMake, in fact, I prefer it over the alternatives such as Sconstruct or Jam. Sorry if my comment sounds as an attempt to put you down, it really isn't. Still, I wonder what kind of practical problem CMake could solve, besides generating an XCode project if someone needs it.

**Comment by winterheart** [comment]
@dimag0g I'm almost done, here my results so far: https://github.com/winterheart/fheroes2/tree/cmake
Some things still need to implement such as integrate to CI and get compilation with SDL2.

Main advantage of using CMake is you don't have re-implement build process each time when project has major changes such as adding new platform, toolchain or a big reorganization. As long CMake has support new features it's easy to update project for new environment.

BTW, I noticed some regressions with -DENABLE_TOOLS options, seems some code cleanup removed required code for them.

**Comment by dimag0g** [comment]
@winterheart Looks neat. Unfortunately I won't be able to test it because devkitPro toolchain that I'm using doesn't have `sdl2_image-config.cmake`

**Comment by ihhub** [comment]
Hi @winterheart , tools are out of building for now after implementation of new rendering engine.
To test that your cmake compilation is correct we have to run at all our CI/CD pipelines to see that it passes on all platforms.
