### ISSUE TITLE
World map, path arrows have different length, while walking outside city 

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2602]
In the original game the first green arrow is shorter
![image](https://user-images.githubusercontent.com/55348946/104712159-4b1be500-5733-11eb-9a68-67e980ae8ca6.png)
than in fheroes2:
![image](https://user-images.githubusercontent.com/55348946/104712216-58d16a80-5733-11eb-8983-dafe6bfc5c66.png)

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

In the original game, the square at the entrance to the castle has the same movement penalty as the terrain under the castle entrance.

In your screen of the original game, the first arrow appears to be the length of the arrow of a move initiated on a snow square (175% penalty), so this is normal.
In your screen of fheroes2, the first arrow seems to have the length of the arrow of a move initiated on a desert square (penalty 200%), so there is indeed a bug.

Now, in the original game, I always found it annoying that the movement penalty for leaving a castle is defined by the type of terrain under the castle entrance.
It's on my list to propose that this penalty should always be 75%, just like the road penalty.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu.
Thanks for your precision! Your experience is priceless!

**Comment by idshibanov** [comment]
Small note that UI is actually fine here, it's movement penalty that is wrong.

**Comment by Branikolog** [comment]
I also noticed, that about a half of my saves has this flaw.
But in other part, when hero walks out of city we have penalty 75... Can't find out the root of this behaviour.

**Comment by ihhub** [comment]
We have 75, 100, 125, 150, 175 and 200 penalties. For each penalty type we have 24 sprites, overall 145 sprites (1 for the cross). It means that for 175 penalty which is a snow we should use sprites 97-120. fheroes2 uses sprite 109 for the case above which is correct while in the original game we have a sprite which corresponds to penalty 150.

I don't think this is bug for our project.

**Comment by ihhub** [comment]
On top of this: you could compare our version of arrows on a snow with the original. You could see that all arrows have different size which means either snow penalty is not 175 in the original game.

**Comment by ihhub** [comment]
According to the manual of the original game `Notice that you get a 25% bonus to movement while traveling on a road.` which makes sense for the case above. 175 penalty becomes 150 penalty but it doesn't work on a movement within a road.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> But in other part, when hero walks out of city we have penalty 75... Can't find out the root of this behaviour.

There is certainly a portion of road right under the entrance of the castle, so the 75% penalty of the road is applied.

Hello @ihhub,

Don't always trust the manual; it can sometimes be wrong or give approximate information.
(Often the manual is even written before the game is completely finished.)

For Snow the manual indicates:
Terrain: No Pathfinding - Basic Pathfinding - Advanced Pathfinding  - Expert Pathfinding
Snow: 175% - 150% - 100% - 100%
As you can see, the progression is not regular (100% instead of 125% for Advanced Pathfinding).
I don't know if this is intentional or a mistake (from the manual and/or during the game).

The penalties should be either:
Snow: 175% - 150% - 125% - 100%

Or:
Snow: 150% - 125% - 100% - 100%

Currently, unless I am mistaken, in fheroes2, it's:
Snow: 175% - 150% - 125% - 100%
Personaly, I'm okay with that (as the progression is more regular). :)

Again, it is the penalty of the terrain the hero is on before the move that must be taken into account and not the penalty of the terrain the hero will be on after making the move.
Take a look at this: https://handbookhmm.ru/2-logistics.

**Comment by oleg-derevenetz** [comment]
I suppose this issue is no longer relevant due to #4626 and #4756 and may be closed.
