### ISSUE TITLE
Adventure map, hero cannot make the last step from a road, if he has not enough movement points

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#3004]
In the original game hero can make the last step from a road (even diagonal), if he has at least 75 movement points.
![image](https://user-images.githubusercontent.com/55348946/112131101-3ac43280-8bda-11eb-971f-51dc72c4fd9c.png)
![image](https://user-images.githubusercontent.com/55348946/112131164-4dd70280-8bda-11eb-9ca8-90984df7bf1d.png)
Current implementation of fheroes2 doesn't allow to run off a road if hero has movement points less than required to make a straight move on a rough terrain. Hero is able to move only over a road (diagonal too), if he has 75 movement points, but not to step off the road:
![image](https://user-images.githubusercontent.com/55348946/112131234-69420d80-8bda-11eb-9787-3d08cae8476b.png)
![image](https://user-images.githubusercontent.com/55348946/112131311-7ced7400-8bda-11eb-9571-072f55d1ee4f.png)

Note, that I've created two same scenarios with the same heroes and make the same steps.

**Comment by Branikolog** [comment]
@idshibanov 
I remember you were working on pathfinding. 
Current implementation is still reasonable (For me personally). If I'm not mistaken, in HoMM3 it is the same. Have you made it intentionally?
The question is: Are we going to make the original behaviour or just make movement logic mathematically more predictable?

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

This problem is not only for the road, the hero can also move on a terrain to another terrain when this should not be possible: https://github.com/ihhub/fheroes2/issues/1986.
This bug is already reported and @idshibanov and @shprotru are working on it normally: https://github.com/ihhub/fheroes2/issues/1986, https://github.com/ihhub/fheroes2/issues/2200, https://github.com/ihhub/fheroes2/issues/2583.

All of issues mentioned here are caused by the same thing: last diagonal move which bypasses regular rules of the game. Technically heroes don't have enough movement points to get there if it's not a "last tile", so this will be a workaround. We're discussing a solution with @shprotru .

_Originally posted by @idshibanov in https://github.com/ihhub/fheroes2/issues/2583#issuecomment-787128041_

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Oh, thanks for introducing the current development stage! So I'm closing the issue as duplicate of other existing issues.

offtopic: You don't use our discord channel. Is there other way I can fast contact you to discuss any questions?

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu
> offtopic: You don't use our discord channel. Is there other way I can fast contact you to discuss any questions?

I do not use all these means of communication in "real time", too distractive and too time consuming.
Also, I like Freedom and I am not always reachable in real time. :)

Maybe you can post in Q&A category in the Discussions forum on GitHub?
But sometimes you will have to be patient. :D

**Comment by Branikolog** [comment]
@LeHerosInconnu 
No problem. I don't want to bother you too much.) 
I will create discussions then if needed.)
