### ISSUE TITLE
Add brew formula for MacOS build

### ISSUE THREAD

**Issue by pshirshov** [ihhub/fheroes2#3143]
It would be great to have a brew tap for easier installation, could you add it please?

**Comment by ihhub** [comment]
Hi @pshirshov , we are going to implement this in the future.

**Comment by pshirshov** [comment]
I hope that this future is more or less benign (pretty please).
Maybe you may consider that at the moment my patreon contribution is actually 1/3 of all the pledges you have there? :3

**Comment by ihhub** [comment]
Hi @pshirshov ,
we're going to do this with an available time from developers. Right now all forces are thrown to fix bugs in the project left from the original team rather than make helper scripts around the game. I can assure you that this will be done before 1.0 release which is targeted this year.

Also for a developer wanting to work on this issue please take a look at [Homebrew Cookbook](https://docs.brew.sh/Formula-Cookbook) as a guide.

**Comment by pshirshov** [comment]
Thanks!

**Comment by ihhub** [comment]
MacOS now supports installation of the project through MacPorts. You can read the description [here](https://github.com/ihhub/fheroes2/blob/master/doc/INSTALL.md).

**Comment by pshirshov** [comment]
Well, macports is not that popular and is not that convenient. While it's very nice to have such option, I won't even try to set it up for just one app :(

Anyway, thanks.
