### ISSUE TITLE
Campaign save files must be different to normal save files

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#323]
We have a partial support of campaign. Right now we create a save file the same for campaign and normal maps while they should be in different sections/formats.

**Comment by eos428** [comment]
Mind if I take this one? :)

So far these look like the stuff needs to be done:
- Create the load game panel instead of directly jumping to LOADSTANDARD
- Make standard, campaign (and MP, but would be out of the PR's scope) save files use different extensions

What I believe should be good to have, but I'd consider this a bonus (or do in a separate PR):
- Use different base directories for saves of each game type
- Able to load through sub-directories and back to base directory

Also, should we differentiate between original and expansion saves like in the base game?

**Comment by ihhub** [comment]
Hi @eos428 , I don't mind if you take this issue.

I don't think we need to differentiate original and expansion saves. It feels a bit weird honestly.

**Comment by eos428** [comment]
I thought the same, wouldn't make sense these days since both the original and expansion use the same game anyway.

**Comment by ihhub** [comment]
Please remember that campaign saves must have some extra information field in order to carry needed stats from one map to another. If you aren't sure how to do this please ask @idshibanov or me.

**Comment by dimag0g** [comment]
I noticed that with this last merge the save game dialog doesn't pre-fill the name anymore. Before the game was saved as `<scenario name>_<day count>` by default.

Was this change intentional? This is a problem for my Switch port where no keyboard is currently implemented. Even on platforms with a keyboard, I think the default save name was a pretty nice feature.

**Comment by ihhub** [comment]
Hi @dimag0g , I'll take a look. I think I know which change causes this.
