### ISSUE TITLE
MacOS build assumes homebrew for libSDL2

### ISSUE THREAD

**Issue by jfcaron3** [ihhub/fheroes2#3532]
The instructions for macos users assume that the user has homebrew for providing SDL2, because it explicitly looks for /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib, which is where homebrew puts this file.

Not everyone uses homebrew, and it is generally not recommended to combine homebrew, MacPorts, or Fink.  I use MacPorts already and it can provide SDL2, but it puts it in /opt/local/lib/libSDL2-2.0.0.dylib.  

I couldn't find a configuration string with the path anywhere, so it's probably compiled directly into the binary.

I should not have to switch packagers just to satisfy a particular path assumption for SDL2.  Is there a way to configure where it looks for the dylib?  Can we add a configuration option or a command-line parameter for where to find the .dylib?

**Comment by jfcaron3** [comment]
Some people in the MacPorts IRC channel helped me to patch this to use the MacPorts locations for SDL2:
from the directory where the fheroes2 binary is, run these commands:
`install_name_tool -change /usr/local/opt/sdl2_ttf/lib/libSDL2_ttf-2.0.0.dylib /opt/local/lib/libSDL2_ttf-2.0.0.dylib ./fheroes2`
`install_name_tool -change /usr/local/opt/sdl2/lib/libSDL2_mixer-2.0.0.dylib /opt/local/lib/libSDL2_mixer-2.0.0.dylib ./fheroes2`
`install_name_tool -change /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib /opt/local/lib/libSDL2-2.0.0.dylib ./fheroes2`

This should help future MacPorts users if this issue never gets resolved.

**Comment by oleg-derevenetz** [comment]
Hi @jfcaron3 Delivering this app as a macOS binary in its current form is AFAIK an interim measure, as we get closer to the release, there are plans to make a homebrew & macports packages instead (not necessary maintained by us, BTW, you can also contribute to the project by becoming a maintainer of such package). Currently you can build binary from source (instead of running downloaded binary) using libraries installed via macports (I personally use macports too BTW, and not homebrew).

**Comment by jfcaron3** [comment]
I don't think I can devote myself to becoming a maintainer.  I just wanted to document the challenge & solution I faced to get this working.  I'm glad there is a plan for later.

**Comment by oleg-derevenetz** [comment]
Hi @jfcaron3 fheroes2 is now available via MacPorts (games/fheroes2).
