### ISSUE TITLE
Missing Code of Conduct

### ISSUE THREAD

**Issue by BobinMathew** [ihhub/fheroes2#3723]
This repo is missing a Code of Conduct.
Cant I give a PR ?

**Comment by ihhub** [comment]
Hi @BobinMathew , this file could be created from a template in 2 clicks. We don't do this because this file is kind of useless as it describes common logic of behavior and people's communication. All destructive, harrass or belittling behavior is strictly unacceptable by the logic. I'm closing this issue.
