### ISSUE TITLE
Incorrect turns of monsters in the battle

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#395]
We do not have "faster monster of opposite army goes first" logic in the game. For example, in this battle:
![image](https://user-images.githubusercontent.com/19829520/79042571-77965400-7c2b-11ea-80bc-1998af00c2bd.png)

Wolves go first, then 5 elves have their turns. Next we use Trolls turn and by logic Elves should go next as they have the same speed as Wolves but instead Wolves have the first turn again, which is wrong in comparison with the original game's logic.

**Comment by ihhub** [comment]
The best place to look for this behavior is `void Battle::Force::UpdateOrderUnits` function.

**Comment by idshibanov** [comment]
Hi @oleg-derevenetz . I wonder if you can take a look at this old game-breaking bug, since you touched related code recently.

**Comment by oleg-derevenetz** [comment]
Hi @idshibanov I don't quite understand what exactly is the bug here :) Wolves had their turn because they have the same speed as elves and they are in the attacking army, then elves, then trolls (because they are slower than others), then everything should repeat in the same order, i.e. wolves, then elves. Why elves should go first? I'm probably not quite familiar with the mechanics of the original game...

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , if opponents have the same speed monsters and player 1 made the last move then player 2 must have higher priority. The same logic applies for every game in series.

**Comment by idshibanov** [comment]
Indeed, attacking army doesn't go first every time, only for the first turn of the battle. All units are sorted by the speed, but if tied game makes sure that initiative alternates between left and right armies.

Example of a turn order:
Left-Fast
Right-Fast
Right-Average
Left-Slow
...next round...
**Right-Fast**
Left-Fast
Right-Average
Left-Slow

**Comment by LeHerosInconnu** [comment]
Yes, a little precision with another example so that everything is clear.
When the fastest troop of each army has the same speed, it is always the fastest troop of the army opposite to the last troop that played the current turn that will play the next turn.

Example:
Tour 1.
Left-Fast
Right-Fast

Tour 2.
Left-Fast  (because last move was made on right side)
Right-Fast

Tour 3.
Left-Fast  (because last move was made on right side)
Right-Fast

**Comment by oleg-derevenetz** [comment]
Hi @ihhub @idshibanov I made some changes (#3095). I hope I understood correctly what needs to be done (I'm not 100% sure about that).
