### ISSUE TITLE
Adventure map, wrong passability of Trees (0.9.6 3976)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4067]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there is a wrong passability of Trees.

In original game:

![Bug passability 101 001](https://user-images.githubusercontent.com/43583994/130363655-67b4452d-645b-4fbe-8cee-8d86cd13562c.png)

In fheroes2:

![Bug passability 101 002](https://user-images.githubusercontent.com/43583994/130363671-5fb2a2ff-703b-4066-8b13-21e12b9fe6ef.png)

### Save file

Here is the save file:
[Bug passability 101.zip](https://github.com/ihhub/fheroes2/files/7027780/Bug.passability.101.zip)

### Additional info

Version 0.9.6 3976.

**Comment by oleg-derevenetz** [comment]
Related to #3949

**Comment by ZsoltMolnarrr** [comment]
Hello!

There is a community made map named "Avalanche", where an important barrier can be bypassed easily.

In OG:
![Screenshot 2021-09-06 21 47 25](https://user-images.githubusercontent.com/4989469/132257374-82197003-ca9c-43cb-aeae-ca0fef3a4c81.png)

In fheroes2:
![Screenshot 2021-09-06 21 51 30](https://user-images.githubusercontent.com/4989469/132257384-959e288f-4635-47f1-8b0a-4a34275cebbd.png)

It would be nice to see a rework or fix on passability, there are several issues in the topic.
I think this issue deserves more priority, since passability is a core feature of the game, and currently it is clearly broken.:(
