### ISSUE TITLE
Not destroyed castle gate remains opened after a troop from a castle crossed the bridge during battle

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#418]
While unit being nearby gates don't close.
![Untitled](https://user-images.githubusercontent.com/55348946/80099652-7ba16a80-8577-11ea-9efd-ddc9934297dd.jpg)

**Comment by shprotru** [comment]
additional info: if creature will die on a bridge, it will be raised, scanner does not check the bodys on the battle field.

**Comment by shprotru** [comment]
@ihhub I have understand about battlefield, and with to ask you to create a new wiki page "Battlefield" with this info:
```
Battlefield in-memory representation

 s00s 01  02  03  04  05  06 ~07~"08" 09 s10s
11  12  13  14  15  16  17 ~18~|19| 20  21
 s22s 23  24  25  26  27 ~28~"29" 30  31 s32s
33  34  35  36  37  38 ~39~|40| 41  42  43 
 s44s 45  46  47  48 [49  50] 51  52  53 s54s
55  56  57  58  59  60 ~61~|62| 63  64  65
 s66s 67  68  69  70  71 ~72~"73" 74  75 s76s
77  78  79  80  81  82  83 ~84~|85| 86  87
 s88s 89  90  91  92  93  94 ~95~"96" 97 s98s

~x~  - tiles filled water
"x"  - tiles with brick walls
|x|  - tiles with shooting towers
[xx] - bridge
sxs  - troop initial point
```
how to determine is dead body exists on a battle cell or not? It should be an array, because not only one dead body could be placed on a tile.

**Comment by ihhub** [comment]
Hi @shprotru , I think you missed the situation when attacking army is in a grouped formation.

**Comment by ihhub** [comment]
I'll try to make some fancy wiki page for this battlefield map. Thank you!

**Comment by shprotru** [comment]
@ihhub yes, I could missing additional information, first of all, I wished to understand what exactly is a battlefield and describe maximum information in one scheme. Types of formations are influence on "troop initial point", and could be removed from this scheme and described on a separate. May be exist necessity in additional schemes per battlefield type, because they could have different obstacles with visual mini preview shots or scheme-nesting screenshots.

**Comment by ihhub** [comment]
Hi @shprotru , still thanks for your work! I'll take another look at your pull request tomorrow as now is pretty late for me :)
