### ISSUE TITLE
Game doesn't switch to english after it was previously run on other language from another folder

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4190]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Run Russian version of game from a separate folder. Choose "Рюсский" language:
![image](https://user-images.githubusercontent.com/55348946/132943530-f737b44f-54a7-45c3-b4b7-941549206904.png)
After closing the application I run English version from another folder. But language doesn't switch to english causing game run without fonts:
![image](https://user-images.githubusercontent.com/55348946/132943601-74a7af0c-3047-4e87-a399-3a9b4d153564.png)
When we enter configure we need to manually set "English".
![image](https://user-images.githubusercontent.com/55348946/132943483-1bbcbd6c-dc3c-4b0b-9027-6ab4277f8b9f.png)
![image](https://user-images.githubusercontent.com/55348946/132943493-db4cc688-a527-4393-adcd-132fbd81a9ee.png)
![image](https://user-images.githubusercontent.com/55348946/132943502-3230d4d2-0517-4109-a7d2-ae007534d5a0.png)

### Save file

Two versions of the OG required.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog there is an issue - since fheroes2 supports languages that wasn't officially supported by the OG, we cannot automatically switch to English if game assets don't support some language. So that is by design.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !
The issue is more about updating the configure file. I mean we have two folders with russian and english versions of the game and two separate fheroes2 applications. Both these applications are affected by the same .cfg file. So, when we start russian - version and choose russian language in options .cfg file remembers that. So when we're runnig english version of the game with other fheroes2 application later, it tries show russian symbols . That happens until we enter options and press at least once language selection button. 
Could we make each fheroes2 application to remember the last chosen language option and rewrite .cfg file on startup?

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog yes, this is by design. Suppose that user selects some language that is not supported by OG assets (e.g. Lithuanian). Game starts, then it detects that assets are English-only. If it resets the game language to English, then it would be wrong, because user deliberately selected Lithuanian via config file. I believe that no auto resets should be done at all, because this breaks things. Also I really don't believe that a regular user would ever play game this way. If user wants to play using different installations with different languages, he should take care by himself, for example, by starting the game using the BAT file that will copy appropriate variant of config file in place.

**Comment by ihhub** [comment]
Hi @Branikolog I think we can close this issue since for most well-used languages we have generated fonts.

**Comment by Branikolog** [comment]
Hello, @ihhub .
Agreed.
