### ISSUE TITLE
Evil interface has incorrect drawings on high resolutions

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#4192]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Set very high resolution like 1400x1050 in my case. Open any map and switch to Evil interface. On right side of the interface observe that the blue portions of the graphics is shifted which is not the case for lower resolutions.

### Save file

![image](https://user-images.githubusercontent.com/19829520/132950031-55eeb834-2144-45ce-9f94-7e1f930d0d9e.png)

**Comment by ihhub** [comment]
Hi @a1exsh , would you mind to take a look at this issue since you've fixed similar recently?

**Comment by a1exsh** [comment]
The problem seems not to be related to high resolution, but merely caused by resolution not divisible by 32.
Also, not only _Evil_ interface is affected.

840x525:
![Screenshot from 2021-09-11 17-46-02](https://user-images.githubusercontent.com/489601/132953610-66522354-d973-4dbc-9b63-a3b24bddd07e.png)
![Screenshot from 2021-09-11 17-45-34](https://user-images.githubusercontent.com/489601/132953612-f2389da4-49e6-42bd-a3f2-cc3ed81c38e0.png)

700x525:
![Screenshot from 2021-09-11 17-43-43](https://user-images.githubusercontent.com/489601/132953613-75b9cda5-256c-4214-8e8b-3ebec57ecae6.png)
![Screenshot from 2021-09-11 17-41-05](https://user-images.githubusercontent.com/489601/132953615-148ca7dd-2dbe-497c-86c9-f7e49b431152.png)

**Comment by a1exsh** [comment]
I think I know what to do here — working on a fix!
