### ISSUE TITLE
Add individual Artifact value for AI

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#4226]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Right now all artifacts for AI are differentiated by 4 group values. This is not correct as some artifacts much more valuable than others even within the same group.

We differentiate the value of artifacts only based on it's Level in `int Artifact::getArtifactValue() const` method.

### Describe the possible solution

For each artifact we have to define its value which could be used by AI to evaluate the quality of certain action.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

I think that the artifact value for the AI should be calculated automatically, so that new artifacts are taken into account without having to change anything.

For example, for Attack, Defense, etc.:

+1 Attack = 1000
+2 Attack = 2000

+1 Defense = 1000
+2 Defense = 2000

For artifacts that act or contain spells (depending on the highest spell the artifact acts on, cumulative values if the artifact contains multiple spells):

Spell level 1 = 500
Spell level 2 = 1000

For artifacts acting on several things, of course, the values are added:
Example with Battle Garb of Anduran:

+5 Attack = 5000
+5 Defense = 5000
+5 Spell Power = 5000
Max Morale = 3000
Max Luck = 3000
Town Portal spell (level 5) = 2500
Value: 23 500

For cursed artifacts:

Hideous Mask:
prevents the wandering creatures from joining the hero = -5000

Fizbin of Misfortune:
-2 Morale = -2000

Tax Lien:
-250 gold per day = -2500

All numbers are given for explanation. :)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , yes. It makes sense. As of now we have too primitive evaluation of artifacts.
