### ISSUE TITLE
Possibly hang when AI trying to conquer a haunted mine

### ISSUE THREAD

**Issue by m-alice** [ihhub/fheroes2#4264]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![2021-09-27_15-27-18](https://user-images.githubusercontent.com/7101860/134913342-a51e2109-1775-4f20-9747-d1bce426ebf8.png)

### Save file

[AUTOSAVE.zip](https://github.com/ihhub/fheroes2/files/7236384/AUTOSAVE.zip)

### Additional info

Mine was haunted by my spell.
Please, use autosave.sav
version 0.9.7 (05 September 2021)
installed on GOG latest version

**Comment by ihhub** [comment]
Running in debug mode shows that AI hero has 2 battles on the same tile and funny thing is that you can control Ghosts for the second battle.

**Comment by vincent-grosbois** [comment]
The issue is because we enter HumanTurn() here :
https://github.com/ihhub/fheroes2/blob/449313f90c1ee98540586c0b98b5a950aa80ff8e/src/fheroes2/battle/battle_arena.cpp#L343
probably instead of AI battle turn

But I'm not even sure what is supposed to happen when AI attacks human haunted mines... are you supposed to control the battle or not?

**Comment by ihhub** [comment]
We shouldn't allow to control the army of captured objects. This was done as a part of experimental options. For human player we don't set the color so the fix should be very obvious.
