### ISSUE TITLE
Adventure map, an AI hero moves adjacent to a wandering troop of Mutant Zombies without an attack being initiated when it should

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#4324]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, an AI hero moves adjacent to a wandering troop of Mutant Zombies without an attack being initiated when it should.

In original game:

![Attack dwarves near mountains 01](https://user-images.githubusercontent.com/43583994/136057021-4054b95b-533b-4385-9a9f-7d6cdf241d68.png)

In fheroes2:

![vlcsnap-2021-10-05-17h35m35s144](https://user-images.githubusercontent.com/43583994/136056759-f8e1abb8-37fb-4ddc-acb9-ab27a4f20f87.png)

https://user-images.githubusercontent.com/43583994/136056823-4e76d0a9-956f-4516-bdf5-ffc96370dd5f.mp4

End the turn.

### Save file

Here is the save file:
[Dominion_0041.zip](https://github.com/ihhub/fheroes2/files/7287236/Dominion_0041.zip)

### Additional info

Version 0.9.7 4306

**Comment by oleg-derevenetz** [comment]
That's because cell with the hero is not accessible directly/diagonally from the cell occupied by Zombies in fheroes2:

<img width="639" alt="Inaccessible" src="https://user-images.githubusercontent.com/32623900/136443667-b21cd95a-97b2-4d22-a91d-f8d4dce7d96e.png">

and Zombies naturally cannot attack the cell that is not accessible by them. Looks like another passability issue/difference.
