### ISSUE TITLE
Combat screen, shadow cursor doesn't apply for unreachable hexes

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4555]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Shadow cursor is not shown for hexes, which are unreachable for active troop.
![image](https://user-images.githubusercontent.com/55348946/140500125-e961b87b-4715-4d79-837e-70b52a8fc044.png)
![image](https://user-images.githubusercontent.com/55348946/140500140-5b9bb28c-416c-42f2-9fde-c618396355f3.png)

While in the OG shadow is visible:
![image](https://user-images.githubusercontent.com/55348946/140500257-088b53fd-fcf6-4620-a2aa-783de01415c4.png)

### Save file

Turn "shadow cursor" option on during any battle.

**Comment by oleg-derevenetz** [comment]
The problem here is that shadow cursor works (intentionally) in a different way in OG and fheroes2. It always highlights just one hex in OG, while in fheroes2 it highlights the exact position that unit will  occupy when moved to this hex (in case of wide units), so if unit is not able to move here, no hexes are highlighted, because there is (obviously) no passability info for unreachable hexes.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
For unreachable hexes we have "X" cursor, which indicates, that a particular movement is unavailable.

**Comment by oleg-derevenetz** [comment]
@Branikolog

> For unreachable hexes we have "X" cursor, which indicates, that a particular movement is unavailable.

Yes, but which hexes should be highlighted in this case (especially in case of wide units) since there is no position that unit may take?

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Since we have rather obvious hex-highlighting for 2-hex creatures....
![image](https://user-images.githubusercontent.com/55348946/140520363-ac3d6c2b-3383-4628-ac26-b78bcb6faeac.png)
... why can't we "shadow" next two hexes with "red-crossed" cursor?
![Highlighting 2](https://user-images.githubusercontent.com/55348946/140520870-537a58bf-348a-4f14-a0fc-ae57ed92007c.png)

**Comment by oleg-derevenetz** [comment]
@Branikolog

> Since we have rather obvious hex-highlighting for 2-hex creatures....

It's not so "rather obvious", because it depends on unit's movement distance and on the terrain. For example:

![screenshot1](https://user-images.githubusercontent.com/32623900/140521967-fe1726d6-595d-4358-a4b4-b4bd2acb7f8c.jpg)

Usually hex under cursor is occupied by unit's head, but in this case it will be occupied by unit's tail, because unit is not fast enough to occupy the hex to the left of the cursor. The same situation may be due to obstacles. Current highlighting uses hex passability information (provided by the pathfinder) to highlight hexes properly. So which cells should be highlighted in this case:

![screenshot1](https://user-images.githubusercontent.com/32623900/140522879-d6c0c8e6-0864-446a-bc7f-78093ba7a48a.jpg)

? I think that in current paradigm the correct answer is "none", because they are unreachable.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Well, actually highlighting one hex is a great deal. Actually, I've created the issue, because it was so uncomfortable to check the exact distance to needed hex, while playing without grid (I'm a huge fan of playing without grid, because it spoils battlefield.) ;)

**Comment by oleg-derevenetz** [comment]
@Branikolog

> I've created the issue, because it was so uncomfortable to check the exact distance to needed hex, while playing without grid

I suppose, for purpose of calculating distance without grid, one cell should be enough. In this case, if hex is reachable by the wide unit, the exact unit's position will be highlighted (two hexes), and if not - only one hex under cursor will be highlighted.

**Comment by Branikolog** [comment]
That's exactly what this issue for. ;)
