### ISSUE TITLE
Add uninstall stage for Makefile

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4646]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Uninstall stage is missing.

### Describe the possible solution

Uninstall should be available for users.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog currently `Makefile` contains just the following targets: `all` (to build) and `clean` (to clean), it is not able to perform the installation (doesn't have the `install` target or something like that) and therefore there is no room for `uninstall` target :)

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
The issue was created based on a feedback from players. Unfortunately, I'm not much familiar with "Makefile"... )
So, we don't need uninstall at all, right?

**Comment by oleg-derevenetz** [comment]
@Branikolog

> So, we don't need uninstall at all, right?

Well, each Linux flavor have its own rules for proper app installation layout, so this problem is left to the package manager of the corresponding Linux flavor (there are also many of them). For example, we have a package for Debian-like Linux distributions (in the `script/packaging/debian` directory), some volunteers may maintain packages for other Linux/Unix flavors in separate repositories (for example, I maintain the MacPorts package for [macOS](https://github.com/macports/macports-ports/tree/master/games/fheroes2)). Such packages are able to perform proper installation and uninstallation. `Makefile`s doesn't have the `install`/`uninstall` stages intentionally, because proper Linux-flavor-aware installation is a bit complex task.

**Comment by ihhub** [comment]
I think this is outside our project scope and it's related to package maintenance. I suggest to close it.

**Comment by Branikolog** [comment]
Sure! Thanks for clarification, @oleg-derevenetz & @ihhub!
