### ISSUE TITLE
Hero nuke himself if he is fleeing and has armageddon spell

### ISSUE THREAD

**Issue by vincent-grosbois** [ihhub/fheroes2#4656]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

- create a hero with 1 unit and only armagedon spell
- have him fight a more powerful army
- hero will cast armageddon, even if that means killing himself

this is because in the code that evaluates the effect of mass spells, we don't check if the spell will destroy our own army. In that case, we should probably never cast the spell

### Save file

none

**Comment by oleg-derevenetz** [comment]
It's often worth to sacrifice a hero with a small army if you will halve a large opponent's army in return. This is real strategy used by human players called "Armageddon hit-and-run". AI may use it as well, why not?

**Comment by vincent-grosbois** [comment]
I'm not sure it was intended that way, here your main hero will also suicide 100% of the time if he has a small army, as long as he does more damage to enemy troops than his

**Comment by LeHerosInconnu** [comment]
Hello @vincent-grosbois and @oleg-derevenetz,

> It's often worth to sacrifice a hero with a small army if you will halve a large opponent's army in return. This is real strategy used by human players called "Armageddon hit-and-run". AI may use it as well, why not?

> I'm not sure it was intended that way, here your main hero will also suicide 100% of the time if he has a small army, as long as he does more damage to enemy troops than his

This happens in the original game.

The combat starts normally, then the AI seeing that it loses casts the Armaggedon spell, either with enough troops to resist the spell before running away if it is an important hero, or without taking into account its troops and even if its hero is lost if it is not an important hero.
Or, the AI has a large army and a troop with a large number of creatures that can resist the Armaggedon spell and is facing an equally large army, and the AI feels that if it combats without the spell it will do less damage, in which case the AI does not hesitate for a second to sacrifice its troops with the Armaggedon spell.

In Heroes 2, the AI's goal is to make the human player lose as many creatures as possible, because creatures are expensive and the human player doesn't necessarily have the gold to buy new creatures (or it will take him a long time) whereas the AI doesn't have this problem of lack of gold and can afford to buy more creatures (at least for a while (as long as there are some available)).

That's why in Heroes 2, the confident human player with a large army can end up losing more than half of his army in a single combat against the AI, making the rest of the game more difficult (and sometimes more interesting), or inciting him to reload and play another strategy.

But as @vincent-grosbois writes, I doubt this is intentional in fheroes2, at least for the moment. :)

**Comment by vincent-grosbois** [comment]
I know there is the strategy of "destroying your army to hurt the enemy hero" but there are a few caveats that are not presents in fheroes2, namely that in fheroes2 your main hero will always destroy all of his army in order to do this, even if that means losing the hero / the map

**Comment by LeHerosInconnu** [comment]
@vincent-grosbois.

> I know there is the strategy of "destroying your army to hurt the enemy hero" but there are a few caveats that are not presents in fheroes2, namely that in fheroes2 your main hero will always destroy all of his army in order to do this, even if that means losing the hero / the map

Yes, I understood that there is a "flaw" currently in fheroes2 about this and that it should be corrected, we are in agreement. :)
