### ISSUE TITLE
Collected artifact info

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#468]
In the original game artifact info can be seen with the [right click] over icon.
Our version has all information shown in a pop up window.
![Artifact info](https://user-images.githubusercontent.com/55348946/81064558-8f878d80-8ee2-11ea-931e-3434af6c538d.jpg)

![Artifact info2](https://user-images.githubusercontent.com/55348946/81064526-81397180-8ee2-11ea-91b4-f8a5e7d7401b.jpg)

**Comment by ihhub** [comment]
Hi @Branikolog . What is the issue with our behavior then?

**Comment by Branikolog** [comment]
> Hi @Branikolog . What is the issue with our behavior then?

I suppose our version be as much close to original, as we can do.
Also this issue is actual for such places as Graveyard or Shipwreck... 
After a victory we cannot check artifact info.
![Shipwreck or graveyard artifact info](https://user-images.githubusercontent.com/55348946/81151138-5e15cd00-8f89-11ea-90eb-bf12034bac63.jpg)
While in original game we can.
![Artifact info3](https://user-images.githubusercontent.com/55348946/81151197-6bcb5280-8f89-11ea-8b0b-d90dbe886ccf.jpg)

**Comment by a1exsh** [comment]
Related to #1969 

There are various Dialogs that may involve artifacts and resources pickup in here: https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/heroes/heroes_action.cpp#L220
As well as `Dialog::ArtifactInfo`: https://github.com/ihhub/fheroes2/blob/8d3f903a137cbfd16d86340f132e55bb249998fc/src/fheroes2/dialog/dialog_spriteinfo.cpp#L31

Probably makes sense to generalize these to make it a single dialog that can accommodate all possibilities.

**Comment by LeHerosInconnu** [comment]
This also poses the problem of the window being cut off when the event description text is long.

![Added artifact info makes too big window 01](https://user-images.githubusercontent.com/43583994/143857920-4fb22f0e-3e76-47cb-9aa5-508b3e62cf53.png)

For this, I suggest to go back to the way the original game works (the description of the artifact is displayed when the player right-clicks on the artifact graphic), which is a way known and used by the player.
This would also standardize the way it works in other event windows, for example when the hero captures artifacts at the end of a won battle.
Also in this window if the player clicks on the artifact graphic (as he is used to do in other windows), nothing happens because the artifact text is already displayed, which can be confusing.

**Comment by a1exsh** [comment]
Well, I sort of like to see the artifact info without the need for clicking on it.

We could make it smarter by deciding based on the screen size — auto-display, if it fits; hide otherwise.

**Comment by LeHerosInconnu** [comment]
Hello @a1exsh,

> Well, I sort of like to see the artifact info without the need for clicking on it.
> 
> We could make it smarter by deciding based on the screen size — auto-display, if it fits; hide otherwise.

I also find that the artifact information also "pollutes" the event description text, and if the artifact is already well known to the player it adds text that is not necessary to have knowledge of. :)

**Comment by Branikolog** [comment]
Hi, guys!
My 5 cents:
Being able to check info of artifact on right click is a common way of interacting within a game. So here I agree with @LeHerosInconnu. We can check info, if we want. There's no need to show everything in the window we watch on the screen.
