### ISSUE TITLE
Moat does not stop the troops

### ISSUE THREAD

**Issue by shprotru** [ihhub/fheroes2#471]
When a unit is caught in a moat tile it must spend the rest of the turn moves.

Edit:
Currently a creature, stopped by a moat can move over it next turn in any direction.
Creature should be able to move only for 1 cell, while walking over moat.
![Moat](https://user-images.githubusercontent.com/55348946/88930294-f6b7a280-d283-11ea-8c49-225fb851657b.jpg)

**Comment by ihhub** [comment]
`Battle::Indexes Battle::Board::GetAStarPath( const Unit & b, const Position & dst, bool debug )` method is responsible for path calculation and requires changes there.

**Comment by Branikolog** [comment]
Currently moat is working. Any walking creature, that steps into moat, stops. And can enter castle only the next turn.
@shprotru, can you, please, make sure, that you still experience this issue?

**Comment by Killbrum** [comment]
I can confirm that the issue isn't reproducible anymore. Can we close it?

**Comment by Branikolog** [comment]
Moat is still not working properly.
![image](https://user-images.githubusercontent.com/55348946/98724972-90bfd880-23a5-11eb-9f63-dca9fe6395c8.png)
If a creature stands in a moat, the next turn it can move over moat any distance. (On a screenshot Unicorns can move to the lowest cell and then enter castle in one turn.

**Comment by Branikolog** [comment]
Sure, we are talking about non-flying troops.
Flying creatures shouldn't be affected by moat.)

**Comment by Killbrum** [comment]
Thank you! I will try to look into the code tomorrow

**Comment by Branikolog** [comment]
@Killbrum 
You're welcome! Always be free to ask me any question or advice here or at our discord. :)

**Comment by Killbrum** [comment]
Before I start. I see that moat has some sort of additional feature. So the code says next:

> The Moat reduces by -%{count} the defense skill of any unit and slows to half movement rate.

is it some sort of fheroes feature/additional config?

**Comment by LeHerosInconnu** [comment]
Hello @Killbrum,

In the original game, the moat information window indicates that the troops are slowed down and become more vulnerable to attacks.

In original game:

![Moat penalty H2 01](https://user-images.githubusercontent.com/43583994/98836817-6ec86380-2442-11eb-87f8-6db22e7a1edc.png)

In the original game, during combat, troops end their movement when they enter the moat.
For vulnerability to attack, I never calculated if they really received more damage when they were in the moat.

Maybe @idshibanov could have more information about this.

The information text for the defense of the castle regarding the moat currently in fheroes2 (-3 to creature defense and halved movement) is one of my proposals for the previous fheroes2 project, but it does not seem to have been fully implemented in the previous project since troops do not suffer a movement penalty to get out of the moat; for the -3 defense penalty, I did not check either.

Since this proposal changes the original way the game works, it should only be included as an option.
But this can wait for Beyond 1.0 version of the game.

In fheroes2:

![Moat penalty fh2 01](https://user-images.githubusercontent.com/43583994/98836862-80117000-2442-11eb-8351-1990181d9c0b.png)

![Moat penalty fh2 02](https://user-images.githubusercontent.com/43583994/98836857-7e47ac80-2442-11eb-95a1-31b65325b2aa.png)

**Comment by Killbrum** [comment]
Thanks a lot for the great explanation! @LeHerosInconnu could you confirm that fheroes implementation works correctly according to fheroes description?

We have two choices here:
1) Moat works as described in fheroes documentation/hints and etc. In this case, we need to re-implement/re-work the whole feature or leave it as is.
2) Moat works incorrectly according to fheroes documentation. In this case, this is a bug.

**Comment by LeHerosInconnu** [comment]
@Killbrum.

> Thanks a lot for the great explanation! @LeHerosInconnu could you confirm that fheroes implementation works correctly according to fheroes description?
> 
> We have two choices here:
> 
> 1. Moat works as described in fheroes documentation/hints and etc. In this case, we need to re-implement/re-work the whole feature or leave it as is.
> 2. Moat works incorrectly according to fheroes documentation. In this case, this is a bug.

So, I did some tests.

In the original game, the defense of the troop in the moat is reduced (but this is not shown in the creature info window) because the Rangers do more damage when the troop is in the moat (2 damage when the troop is not in the moat, and 3 damage when the troop is in the moat).
In the original game, the speed of the troop in or out of the moat remains the same.

In original game:

![Moat penalty H2 10](https://user-images.githubusercontent.com/43583994/98861904-50745f00-2466-11eb-8d0b-ffc78d52a345.png)
![Moat penalty H2 12](https://user-images.githubusercontent.com/43583994/98861921-55d1a980-2466-11eb-97d1-53f9060c6f37.png)
![Moat penalty H2 11](https://user-images.githubusercontent.com/43583994/98861914-5407e600-2466-11eb-9c48-ac97d43481d0.png)
![Moat penalty H2 13](https://user-images.githubusercontent.com/43583994/98861926-579b6d00-2466-11eb-9df0-0f17dddd5057.png)

In fheroes2 currently, troops in the moat do have a penalty of -3 in defense, but their speed is not reduced as indicated.

Troop of Champions: Defense Skill "11" outside the moat and Defense Skill "8" in the moat.
Troop of Archers: Defense Skill "5" outside the moat and Defense Skill "2" in the moat.

Troop of Champions: Speed "7" outside and in the moat.
Troop of Archers: Speed "2" outside and in the moat.

In fheroes2:

![Moat penalty fh2 10](https://user-images.githubusercontent.com/43583994/98862009-7b5eb300-2466-11eb-9949-3d707c0233c9.png)
![Moat penalty fh2 11](https://user-images.githubusercontent.com/43583994/98862013-7d287680-2466-11eb-8750-13f3344c53b1.png)
![Moat penalty fh2 12](https://user-images.githubusercontent.com/43583994/98861995-7699ff00-2466-11eb-94e7-f5610b0d57d2.png)
![Moat penalty fh2 13](https://user-images.githubusercontent.com/43583994/98862004-78fc5900-2466-11eb-8bd0-ff7f8c8bddc0.png)

Normally with the proposal, the speed should be halved (same effect as the Slow spell).
And if the Slow spell is active on a troop in the moat, the speed is halved again.
In any case, the speed cannot be less than "1".

For the current fheroes2 project, the intention is to stay as close as possible to the original game at first (at least until version 1.0 of fheroes2).
This is why this change must be applied as an option, so that version 1.0 of fheroes2 is as close as possible to the original game.

So for the moment, fheroes2 does not work as shown in this screen (for halved movement), and at the same time, with the new fheroes2 project, this should be an option.
And this option can be implemented later (if it requires a lot of development time) for Beyond 1.0 of fheroes2.
![Moat penalty fh2 02](https://user-images.githubusercontent.com/43583994/98836857-7e47ac80-2442-11eb-95a1-31b65325b2aa.png)

So there are two possibilities: :)

1) Either, leave it as it is now and modify the text (the "-" of "-3" is redundant):

"The moat reduces by 3 the defense skill of any unit."

Instead of:

"The Moat reduces by -3 the defense skill of any unit and slows to half movement rate."

2) Or (this can be done later), add the option "Battle: The moat halves the speed of the creatures" and modify the text when the option is activated: 

"The Moat reduces by 3 the defense skill of any unit and slows to half movement rate."

**Comment by ihhub** [comment]
Hi @Branikolog , could you please verify this issue?

**Comment by Branikolog** [comment]
@ihhub 
Issue is still on.
Creatures continue walking on a water without penalties...

**Comment by Branikolog** [comment]
The issue is gone. Troops cannot walk over the moat freely anymore.
