### ISSUE TITLE
Adventure map, Town Gate spell shouldn't be proceed if hero casts it from the castle

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#4771]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

While casting "Town Gate" spell standing inside a town hero makes teleportation  inside town wasting spell points to nowhere.
While in the OG pop up message appears.
![image](https://user-images.githubusercontent.com/55348946/145571981-b20fe07c-b11b-47cb-a639-349c99fe4621.png)
I also want to suggest to change a bit message to: "You're already in a town. Spell failed".

### Save file

[Uploading Town Gate.zip…]()

**Comment by LeHerosInconnu** [comment]
I'm reposting this here, for the way to tell the player that the nearest castle is already occupied.
The suggestion to not allow spells to be used directly in the hero's Magic Book, under certain conditions, for adventure spells and combat spells should preferably be dealt in another issue I would create later.

*

Hello @ihhub,

> Hi @LeHerosInconnu , I think specifying town or castle for **Town** Gate spell might be unnecessary. I suggest to leave the implementation as it is.

The precision of the town or castle is important for decision making because, for example, the player may want to send his hero to a castle where he can recover his spell points thanks to the presence of a Mage Guild or recruit creatures, and this is more likely to be possible in a castle than in a town (so the player can evaluate this without having to exit the Magic Book window and go check).

The Town Portal spell allows to have this kind of information because a list of towns and castles is displayed allowing to right-click on the city graphic to have additional information (creatures in garrison for example).

And adding the graphic of the town or castle in the Town Gate spell information window would not allow to right click on this graphic to have additional information when this window is already opened with the right click (temporary window without "OKAY" button).

> Some users might ask why not just disable spell then instead of showing extra info?

I have already planned to not allow spells to be used directly in the hero's Magic Book, under certain conditions, for adventure spells and combat spells.
For example, for the Town Gate spell, the nearest castle is already occupied by one of the player's other heroes, or the hero trying to cast the spell is already in the nearest castle, or the player no longer has a castle, etc.
This is part of my long list of suggestions not yet posted. :)

But it does tell the player why he can' t do it, and it does so directly in the spell info window.

So, with the current functioning, if the player sees in the spell information window that the castle is occupied for example by the hero to whom he wants to cast the spell, he will not do it and will not waste 10 spell points stupidly (in the current version of fheroes2, if the hero who wants to cast the Town Gate spell is already in the nearest town he can still cast the spell). :)

> Regarding Hypnotize spell: this spell has not only HP limit but also duration. Are we going to display both? I think we can do this in a separate pull request if you're okay with this.

The duration of the Hypnotize spell (duration depending on the hero Spell Power, limited to one attack) should rather be specified in the spell description (to be done in another PR).
And if a modification of the duration or the initial functioning of the spell is altered, it would be better to add one or more sentences to describe the effect of this or these changes.

_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/issues/4761#issuecomment-991092511_

*

Hi @LeHerosInconnu , I think all changes for Town Gate spell should be done separately :) @Branikolog even created an issue for this and we can expand the changes there.

Duration of spells will be done separately as I'd like to keep changes minimal.

_Originally posted by @ihhub in https://github.com/ihhub/fheroes2/issues/4761#issuecomment-991103354_

**Comment by LeHerosInconnu** [comment]
To avoid this horrible "Spell Failed!!!" window (no such window should appear in the game), :) I suggest making a spell that cannot be cast for whatever reason "greyed out" (the spell text) in the Magic Book in the same way that a spell is greyed out when the hero does not have enough spell points to cast the spell, and that therefore it is not possible to cast the spell.

In fheroes2:

The spell's "greyed out" text in the Magic Book.
![Greyed spell 001](https://user-images.githubusercontent.com/43583994/145685229-478acc44-930c-4332-838c-35f5562e97cc.png)

If the player attempts to cast the spell anyway, this window is displayed.
![Greyed spell 002](https://user-images.githubusercontent.com/43583994/145685237-7fccc3a9-1e5c-4660-9c9a-6f0a2eac72b5.png)

The spell information window should also tell the player why it is not possible to cast the spell.

In the case of the "Town Gate" spell, the spell should not be able to be cast when:

- There is already one of the player's heroes (it could also be the hero who would like to cast the spell) occupying the nearest town or castle.
The text to be displayed (in the spell information window), separated by a line of empty text, could be:

"The nearest castle is Westfork.

This castle is occupied by your hero Rialdo."

I think it is not necessary to display a different sentence if it is the hero who is already in the nearest town or castle who wants to cast the spell.

Also it would be nice to specify in the sentence if it is a "town" or a "castle" depending on the case (this gives the player information for decision making, see post above):

"The nearest town is Westfork.

This town is occupied by your hero Rialdo."

If the player attempts to cast the spell anyway, the window text could be:
(The name of the spell should also be added as a yellow title (see **Note:** below).)

"This town is occupied by your hero Rialdo, so you can't cast the spell."

- The player does not control a town or castle.
The text to be displayed (in the spell information window), separated by a line of empty text, could be:

"The nearest castle is Westfork.

You do not currently own any town or castle."

If the player attempts to cast the spell anyway, the window text could be:
(The name of the spell should also be added as a yellow title (see **Note:** below).)

"You do not currently own any town or castle, so you can't cast the spell."

- And of course, the hero does not have enough spell points to cast the spell.
The text to be displayed (in the spell information window), separated by a line of empty text, could be:

"The nearest castle is Westfork.

You don't have enough mana to cast this spell."

If the player attempts to cast the spell anyway, this window already exists (see above).
**Note:** The yellow title "Visions" should be added to this window. (https://github.com/ihhub/fheroes2/issues/4780)

For the other spells affected by this "Spell Failed!!!" (or other message) window, I'll do it in another issue or several other issues. :)
Related issue: https://github.com/ihhub/fheroes2/issues/1704.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu 

With all that suggestions, this spell is going to become really comfortable and predictable! 👍 

>"This town is occupied by your hero Rialdo, so you can't cast the spell."

Personally I prefer more general statement "... by one of your heroes..." so we leave mind focus of a player on a castle name.

>I think it is not necessary to display a different sentence if it is the hero who is already in the nearest town or castle who wants to cast the spell.

Why not? Players not always remember the name of their heroes or towns, so if the spell will indicate the fact, that hero cannot cast this spell while visiting a town will clearly explain what is he doing wrong.
All your other suggestions on initiating the spell in different circumstances are great, this one will definitely make spell operation more clear.

>Also it would be nice to specify in the sentence if it is a "town" or a "castle" depending on the case (this gives the player information for decision making, see post above):

Adding castle icon to spell dialog brings visual image of castle existence in a town, so player will definitely understand what type of town he is going to teleport to. As well as check with right click all other information about this town.
Also, the spell is named "Town Gate", so word  "towns" appeared in the spell description is quite predictable. ;)


P.S. Sorry, if I've understood something wrong in your messages. ;)

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Hi, @LeHerosInconnu
> 
> With all that suggestions, this spell is going to become really comfortable and predictable! +1

This is the goal, to have an enjoyable game to play. :)

> > "This town is occupied by your hero Rialdo, so you can't cast the spell."
> 
> Personally I prefer more general statement "... by one of your heroes..." so we leave mind focus of a player on a castle name.

The player can attempt to cast the spell directly without consulting the spell information window.
Unlike towns and castles, heroes have their own portrait.
Some players know the portrait that matches the name, so it is more convenient to select the hero directly from the list on the adventure map screen based on the portrait that matches the name displayed in this information window.

Now, it's also possible to add the hero's portrait in the spell information window (and even in this window, but I don't think it is desirable, this window should be kept simple and succinct), but I'm afraid that the spell information window will become too graphically crowded.
Also by indicating the castle name and the hero's name  in the spell information window, the player can make his search according to what he knows best. :)

> > I think it is not necessary to display a different sentence if it is the hero who is already in the nearest town or castle who wants to cast the spell.
> 
> Why not? Players not always remember the name of their heroes or towns, so if the spell will indicate the fact, that hero cannot cast this spell while visiting a town will clearly explain what is he doing wrong. All your other suggestions on initiating the spell in different circumstances are great, this one will definitely make spell operation more clear.

This may be necessary for some players, yes.
So, the text to be displayed (in the spell information window), separated by a line of empty text, could be:

"The nearest castle is Westfork.

This castle is occupied by your hero Rialdo, the one from which you consult this Magic Book."

If the player attempts to cast the spell anyway, the window text could be:

"This castle is occupied by your hero Rialdo, the one from which you try to cast this spell, so it's not necessary to cast this spell."

Or: :D

"Westfork castle is occupied by your hero Rialdo, the one from which you try to cast this spell, so it's not necessary to cast this spell."

> > Also it would be nice to specify in the sentence if it is a "town" or a "castle" depending on the case (this gives the player information for decision making, see post above):
> 
> Adding castle icon to spell dialog brings visual image of castle existence in a town, so player will definitely understand what type of town he is going to teleport to. As well as check with right click all other information about this town.

As I wrote in a post above:

"And adding the graphic of the town or castle in the Town Gate spell information window would not allow to right click on this graphic to have additional information when this window is already opened with the right click (temporary window without "OKAY" button)."
This while the Magic Book is opened when the player is about to cast the spell on the adventure map, not when the player consults the Magic Book from the hero screen.
Unless to provide a specific window for each case.

> Also, the spell is named "Town Gate", so word "towns" appeared in the spell description is quite predictable. ;)

The Town Gate spell description states:

"Returns the caster to any **town** or **castle** currently owned."

Might as well give the player the precise information about it in the sentence indicating the name of the city. :)

In fheroes2:

![Nearest town occupied 02](https://user-images.githubusercontent.com/43583994/145252311-9ed8c2f9-eff7-4f05-ad23-76a0447f68ec.png)

> P.S. Sorry, if I've understood something wrong in your messages. ;)

No worry. :)
