### ISSUE TITLE
Unit animation is freezed during its turn

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#487]
The current unit animation is freezed at one certain frame. You can notice, that elves' eyes are always closed, during their turn.
![Sleeping elf](https://user-images.githubusercontent.com/55348946/81475750-c3322280-9216-11ea-87ef-6620380f0976.jpg)

**Comment by shprotru** [comment]
Don't sure, but possible fix for this issues is [here](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/battle/battle_interface.cpp#L1163), in function [RedrawTroopSprite](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/battle/battle_interface.cpp#L1156) replacing  `msi.frm_idle.start` to `b.GetFrame()`, visually look's much better. Possibly reason: no need in usage of frm_idle.start because exists function [SetIdleAnimation](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/battle/battle_army.cpp#L384)

@ihhub too much amount of code written in one-line style, this is difficult to debug. For example, [GetMonsterSprite](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/monster/monster.cpp#L1769)
**all** places with ternary operators and places with logic operators placed in one-line style. Example is [OutOfWalls](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/battle/battle_troop.cpp#L452).
Is it allowed to refactor it in PR's making it multi-line? Or will create an active issue for asking you quickly refactor small things by request there?

**Comment by ihhub** [comment]
Hi @shprotru , we allow to refactor the code if it makes the code better for readers and/or faster :)

**Comment by ihhub** [comment]
> Don't sure, but possible fix for this issues is [here](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/battle/battle_interface.cpp#L1163), in function [RedrawTroopSprite](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/battle/battle_interface.cpp#L1156) replacing `msi.frm_idle.start` to `b.GetFrame()`, visually look's much better. Possibly reason: no need in usage of frm_idle.start because exists function [SetIdleAnimation](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/battle/battle_army.cpp#L384). See your `TODO` [here](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/battle/battle_animation.cpp#L204) but not understand what you mean, hope, it's for another issue.
> 
> @ihhub too much amount of code written in one-line style, this is difficult to debug. For example, [GetMonsterSprite](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/monster/monster.cpp#L1769)
> **all** places with ternary operators and places with logic operators placed in one-line style. Example is [OutOfWalls](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/battle/battle_troop.cpp#L452).
> Is it allowed to refactor it in PR's making it multi-line? Or will create an active issue for asking you quickly refactor small things by request there?

**TODO** is being fixed in another pull request for animation. We'll merged it very soon :)
Regarding **OutOfWalls**: it is not a ternary operator but a multi-case statement.

Also making some changes please always keep in mind performance.
