### ISSUE TITLE
AI should upgrade magic guild more often

### ISSUE THREAD

**Issue by Mergpijp** [ihhub/fheroes2#5046]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

The end game of heroes 2 is sometimes a bit to easy. Although the game is notoriously hard on some maps.
I was watching a stream and this expert player suggested that the AI should focus more on building the magic guild.

### Describe the possible solution

If the AI has more spells the end-game will be harder because the spells are so good in this game.

### Additional info

I know this is a balance change but since you changed the AI I thought this was reasonable as well.

**Comment by idshibanov** [comment]
Firstly I want to say that AI shouldn't blindly upgrade every magic guild since we have to make sure it will be more beneficial to the AI rather than human player (lack of good spellcasting heroes for example). In my experience playing original Heroes 2 on higher difficulties it was much more efficient to let AI build up magic guilds in cities and then capture them rather than upgrade them myself.

I agree that we should definitely increase priority on high level magic guilds. However first we've got to start with improvements to castle defense logic and take in account how defensible the castle is to avoid it being exploited.

**Comment by Kiiro-Yakumo** [comment]
Hmm, the commander defending the castle if no other heroes is present can cast spells up to level 2 so at the very least AI could go to level 1 or 2 I guess? Plus let's not forget that casting spells is not so simple as to just "throw them" at the enemy. I still have fheroes2 for Android, very old build from previous team and AI could go so far as to cast fireballs... at my black dragons...

Plus remember that Mage Guild is technically most "expensive" building in that matter that it requires all the resource types in increased ammounts. It's easy to just focus on Mage Guild and give yourself disadvantage because you may even not be able to cast the spells as of yet but the resources are spent already.

**Comment by ihhub** [comment]
Hi @Kiiro-Yakumo , I don't think that having spells for a commander gives a victory to AI against a player. Everything should be rational and AI must behave to maximize chances of its victory, not to blindly use all resources available. In other words, building mage guilds must be rational based on a state of a game.

**Comment by Kiiro-Yakumo** [comment]
Yeah that's what I meant, I just didn't put it properly into words I guess, my bad.
Sure the spells are not "auto-win" in any way. They are just options.
I guess as a bare minimum AI could try to go this way:
If nothing else to build -> Attempt to build Guild Mage level 1-5
For something more advanced, we would have to do some strategy probably, how "smart" AI - per difficulty level - should be about deciding that "today, we will build another Guild Mage floor and that's that!" is a good idea.

**Comment by ihhub** [comment]
This is what AI is doing right now :) The problem is that many player think that AI has unlimited resources to build everything but it has the same amount of resources as a human player.

**Comment by Kiiro-Yakumo** [comment]
Ah that part. If memory serves that was the not-so-big mystery of the Heroes 2 and 3 (and maybe others?). The original AI wasn't much different between difficulty settings, maybe not different at all. The only difference was the starting resources, on lowest player had more, on highest CPU had more. However that's for the original game files. From what I have observed across the time both fheroes2 and HotA (Heroes 3) and to some extend VCMI (Heroes 3) I think as well, were able to make AI more competent in what it does. Even on easy - yeah I'm casual - AI is not so stupid to allow me to just waltz in as I please. That's a success in my book.

As for the Guild Mage levels hmm... actually it may be a bit of a "problem" depending how we approach it. First of all, not every character will have Wisdom Skill from the start or across the game even. That's the first step for "do we really need a tower for a bunch of people in robes here?" (Is what a Barbarian character would probably say). Second is "what spells do we have here" and are they useful to the current map, situation and so on. Making AI to consider everything is not an easy task.

Nevertheless AI for sure doesn't have unlimited resources. It's actually easy to check. For those interested, make a custom map where AI has no access to the mines and block building trading post. You will see that AI will be blocked out at some point.
