### ISSUE TITLE
Well: Wrong message when buying max troops without enough slots

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#5236]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Other

### Describe the bug

In the well when you try to buy max troops and all slots are already occupied, you get the message saying you don't have enough resources instead of any free slots.

![image](https://user-images.githubusercontent.com/12501091/162635173-8a417a22-1907-4a55-b6a7-770f14d14523.png)

![image](https://user-images.githubusercontent.com/12501091/162635146-4f8665ba-d6af-4662-9ee4-80f48e0ddeb4.png)

The resources are hardly the problem why I can't buy 12 peasants.

### Save file

Just open the well and fill the slots on beforehand.

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

Here, I suggest to add a yellow title to the window (for all cases):

"Recruit Creatures"

A suggestion for the case the the army is full:

"You are unable to recruit at this time, your ranks are full."

From original game:

![Army full 01](https://user-images.githubusercontent.com/43583994/168481439-7d5110bd-76b9-4121-a32b-a349f44c6c11.png)

Replace "buy" by "recruit" in the text (in case there are not enough resources):

"Not enough resources to recruit creatures."

Instead of:

"Not enough resources to buy creatures."

I can open new issues if necessary.

**Comment by zenseii** [comment]
> 

Hi @LeHerosInconnu ! I initially wanted to reuse the phrase we already have to avoid needing more translations: 
"There is no room in the garrison for this army."

But it didn't sound so good in this case so I changed it slightly to this:
"There is no room in the garrison for new creatures."
![image](https://user-images.githubusercontent.com/12501091/168481686-b0b8e7c4-0308-4961-9979-d685b6052e32.png)

**Comment by LeHerosInconnu** [comment]
@zenseii.

> > 
> 
> Hi @LeHerosInconnu ! I initially wanted to reuse the phrase we already have to avoid needing more translations: "There is no room in the garrison for this army."
> 
> But it didn't sound so good in this case so I changed it slightly to this: "There is no room in the garrison for new creatures." ![image](https://user-images.githubusercontent.com/12501091/168481686-b0b8e7c4-0308-4961-9979-d685b6052e32.png)
> 
> The only problem is that garrison doesn't necessarily sound like your guest hero's army, which could also be the case being full here.

That's why I came up with a phrase from the original game with "your ranks" which is more general. :)
