### ISSUE TITLE
The same music in Barbarian and Wizard city

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#526]
The same soundtrack plays in both of this cities.

**Comment by idshibanov** [comment]
@Branikolog this is a known issue in Succession Wars (original release, demo version as well). They not only have the same music, MIDI version was assigned to wrong cities. You can compare to the full tracks here: https://www.youtube.com/watch?v=VRcprUCjwDc. There's only 5 MIDI tracks and 6 cities, so one of them would repeat.

Fixed by #523
