### ISSUE TITLE
Bulgarian language not working

### ISSUE THREAD

**Issue by Effektus** [ihhub/fheroes2#5477]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When click on Bulgarian language radio button nothing happened.

### Save file

When click on Bulgarian language radio button nothing happened.

### Additional info

When click on Bulgarian language radio button nothing happened.

**Comment by ihhub** [comment]
Hi @Effektus , Bulgarian translation is almost empty. Nobody from our team is working on it. That is why nothing happens within the game. You can contribute by helping to translate the game to this language.

**Comment by Effektus** [comment]
Ok how to help with translating?

**Comment by zenseii** [comment]
Thank you for wanting to comtribute @Effektus ! Note that some parts have become easier with regards to translation. For example for Bulgarian you do not need to install cygwin if you are on windows. You only need poedit for the whole process, which I strongly recommend compared to just a source code editor like notepad++.

**Comment by Effektus** [comment]
Which file to use as a basis, I can't find English?

**Comment by zenseii** [comment]
The file for Bulgarian already exists as `bg.po`:
https://github.com/ihhub/fheroes2/blob/master/files/lang/bg.po

In case you, do not know, hold alt pluss click on "RAW" to download that file.
![image](https://user-images.githubusercontent.com/12501091/170959222-2d9f16ab-1907-4844-95bc-6af7b1dd47a6.png)

**Comment by Effektus** [comment]
O yes sorry i'ts clean and ready for translation. Thanks

**Comment by zenseii** [comment]
> O yes sorry i'ts clean and ready for translation. Thanks

Please note that we also want to avoid having 1000 lines of translations added in one PR/a single submission, because this ends up slowing down the translation process. The best approach is to do small parts at a time, like maybe 80 lines of one area of the game (like all creature names) and then submit that.

**Comment by Effektus** [comment]
I test all menu Translation but don't look well. I make couple of changes and after save copy and paste "bg.mo" file in "fheroes2_windows_x64_SDL2\files\lang" but the result is not good. And one more thing I can find "Yes" and "No"

![image](https://user-images.githubusercontent.com/12934196/170984210-25dc9bb6-7776-4972-87d6-01b4a889b243.png)

**Comment by zenseii** [comment]
> I test all menu Translation but don't look well. I make couple of changes and after save copy and paste "bg.mo" file in "fheroes2_windows_x64_SDL2\files\lang" but the result is not good. And one more thing I can find "Yes" and "No"

Yes, what you need to do is change the settings in poedit when compiling the .mo. You need to go to "Translations"->"Properties" and change Charset to "CP1251" as seen in the image below:

![image](https://user-images.githubusercontent.com/12501091/170985119-23d6273a-3fc9-4a22-b465-b2c644d14ee5.png)


When you submit your changes to the translation the bg.po will need to be saved back again to UTF8.

Changing to CP1251 while testing and then back again is much faster and more convenient than the alternative of installing cygwin.

**Comment by oleg-derevenetz** [comment]
Hi @zenseii

> Note that some parts have become easier with regards to translation. For example for Bulgarian you do not need to install cygwin if you are on windows. You only need poedit for the whole process, which I strongly recommend compared to just a source code editor like notepad++, which would require cygwin if on windows.

Would you mind to update the `TRANSLATION.md` manual to reflect the latest changes in tooling requirements and translation process on Windows, since you are familiar with this? The manual seems a bit outdated now because content of `po` files is now automatically updated using our CI, so there is no need to perform merge by hand anymore (except maybe in some edge cases, e.g. when the code was updated in the same PR), etc.

**Comment by zenseii** [comment]
> Would you mind to update the `TRANSLATION.md` manual to reflect the latest changes in tooling requirements and translation process on Windows, since you are familiar with this? The manual seems a bit outdated now because content of `po` files is now automatically updated using our CI, so there is no need to perform merge by hand anymore (except maybe in some edge cases, e.g. when the code was updated in the same PR), etc.

Hi @oleg-derevenetz!
Yep, I agree this should be done and I had already thought about doing it I just got busy with the other PR. I'll get on it now since it should be quick and simple to address.

**Comment by ihhub** [comment]
Hi @Effektus , any progress on translation?

**Comment by Effektus** [comment]
Yes I have little progress of menu. Sorry I don't have much time last days but now i will have more.

**Comment by KaiserDMC** [comment]
Hi @Effektus, let me know if you need any help with the translation or proofreading. I'd gladly lend a hand! ;)

**Comment by Effektus** [comment]
Sorry but now I see there are new version of my language file with more words in there. I have started working on old version, Is there a way to merge or .... copy row by row?

**Comment by Effektus** [comment]
I start working on last version of file, but please warrnig me when you plan to realease new version. ;)

**Comment by Effektus** [comment]
First version 

![image](https://user-images.githubusercontent.com/12934196/175815906-3172822e-5a51-4953-bd15-a6e4006bf6e9.png)

[bg.zip](https://github.com/ihhub/fheroes2/files/8986685/bg.zip)

**Comment by zenseii** [comment]
> First version
> 
> ![image](https://user-images.githubusercontent.com/12934196/175815906-3172822e-5a51-4953-bd15-a6e4006bf6e9.png)
> 
> [bg.zip](https://github.com/ihhub/fheroes2/files/8986685/bg.zip)

Hi @Effektus ! Thank you a lot for sharing this and sorry for not coming back to you earlier. Would you be able to share this translation in a PR to this repository? This is how we prefer to deal with new additions to the project.

**Comment by Effektus** [comment]
Sorry but I will need help how to share PR in to this repository!

**Comment by zenseii** [comment]
> Sorry but I will need help how to share in a PR in to this repository!

No worries.

First you will need to fork this repository so that you have your own repository:
![image](https://user-images.githubusercontent.com/12501091/178440160-b59fef3e-d24e-424b-a81a-1a747714fc93.png)

Then, unless you are familiar with other methods, the easiest way to add your changes is to use github desktop:
https://desktop.github.com/

Within that app you will need to clone your fheroes2 repository, which could be named something like **effektus/fheroes2**. It might be easier to do by typing the URL:
![image](https://user-images.githubusercontent.com/12501091/178440657-d9ea6e4b-e2eb-4874-8579-52fc1f57892d.png)

Then a good practice is to create a new branch and publish it to your own online repo:
![image](https://user-images.githubusercontent.com/12501091/178441028-cf67210b-e362-4893-b09d-8fb4da45a344.png)

Go to the location of your local clone on your PC. This can be done from this shortcut:
![image](https://user-images.githubusercontent.com/12501091/178441507-51890977-ab70-4da9-a922-bd56bc764b73.png)

Navigate to `files/lang` within that clone and copy-paste your edited `bg.po` over the `bg.po` that is present in that folder: 
![image](https://user-images.githubusercontent.com/12501091/178441791-a93515e6-07c9-444f-b772-298ec50fcc51.png)

At this point you should see that github desktop registers a change being present:
![image](https://user-images.githubusercontent.com/12501091/178442029-7f6d8caa-fc2a-4770-93fa-3330692b2b55.png)

Confirm your changes by pressing `Commit to [name of your branch]`:
![image](https://user-images.githubusercontent.com/12501091/178442219-8e3496b7-2918-4e21-a5dd-11f3ec4c3664.png)

Then push your changes, and afterwards you will be able to press `Create Pull Request`:
![image](https://user-images.githubusercontent.com/12501091/178442544-802c60c5-e3ba-4b6c-a7bb-18de739fbfc5.png)

If there are no conflicts with ihhub/fheroes2 you will be able to post your pull request (PR):
![image](https://user-images.githubusercontent.com/12501091/178442939-ff186d3d-a4ca-4746-9391-9faa7ac61df0.png)

The rest we will take from there.

**Comment by Effektus** [comment]
Ok, thanks for the pull request tutorial ;) I did it. Is everything okay now?

**Comment by ihhub** [comment]
I am closing this issue as we added initial support of Bulgarian language.
