### ISSUE TITLE
Adventure map, wrong monster spawn according to the "Random Monster 1 (weak)" object

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5538]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Based on a feedback from our community.
"Random monster" object has 4 different levels.
Level 1 spawns 1st tier and some weak 2nd tier monsters.
Original game:
![image](https://user-images.githubusercontent.com/55348946/173523718-3a819efa-8782-4fe6-b5ad-250b369657d5.png)
And the same works for fheroes2 in a custom maps.
But on a particular map "Skirmish" "Random monster 2" seemed to be spawned, where "1" should, according to the editor:
![image](https://user-images.githubusercontent.com/55348946/173524694-bfab00cf-c23b-4ceb-902e-6761cac2d757.png)
Original game:
![image](https://user-images.githubusercontent.com/55348946/173524964-e24a552a-e2d0-454c-9900-fcc26d5c907c.png)
fheroes2:
![image](https://user-images.githubusercontent.com/55348946/173525233-d5ed52d4-91f6-43de-87c6-d8035c78c5a8.png)

At the same time when I place some "Random monster 1" manually on this map, newly placed monsters spawn according to the rule correctly.
![image](https://user-images.githubusercontent.com/55348946/173526324-263513ce-05d3-4e1a-9dbf-033764917735.png)
fheroes2:
![image](https://user-images.githubusercontent.com/55348946/173526056-dfe4952e-3bca-47cf-a314-01ab35b7515b.png)

### Save file

[Skirmish_Spawn.zip](https://github.com/ihhub/fheroes2/files/8897735/Skirmish_Spawn.zip)

**Comment by oleg-derevenetz** [comment]
Yeah, interesting issue. Despite the fact that editor shows `MON1` (`0xB3`) on that tile, in fact in the map file itself it's `MON2` (`0xB4`). At the same time, if I place `MON1` on some other tile using the same editor, it is correctly written to the map file as `MON1` (`0xB3`) and the proper monster is spawned. So, according to the map editor, sometimes `0xB4` means `MON1` and sometimes it means `MON2`. The logic is absolutely unclear.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
This happens only on this particular map... I've checked a few other maps: Mon1 spawns correctly there...

**Comment by oleg-derevenetz** [comment]
Okay, I figured it out, but I still can't say, how to better fix this (and is it worth to fix it at all).

The thing is, tile has `mapObjectType`, which is `0xB4` (`OBJ_RNDMONSTER2`) for problematic tile (i.e. roughly speaking this means "random monster of level 2", but the real rules are little more complicated), BUT at the same time it has `level1IcnImageIndex` (which is index of object image on that tile - in this case it's that placeholder image in the form of a circle with the inscription, which is visible in the editor and which will be then replaced by a REAL monster image), which is `0x43` (the image with `MON1`).

So I have an idea that, when an actual monster is generated in place of that placeholder, the original game looks at the placeholder's image index (`level1IcnImageIndex`), while our engine looks at the actual object index (`mapObjectType`). Usually they are in sync (and so it should be), BUT this particular map is generated using some buggy map editor (not the original editor, because original editor keeps all these fields in sync), and that buggy editor failed to keep these fields in sync.

BTW it's not the only tile on this map where `level1IcnImageIndex` doesn't match the `mapObjectType`.
