### ISSUE TITLE
Ultimate Artifact placed on square which cannot be dig

### ISSUE THREAD

**Issue by SlavisaBelic** [ihhub/fheroes2#5563]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Map Dead Dragons. Ultimate Artifact placed on already digged hole. See screenshot. In the beginning I have tried to search every square around it. After I completed map I have visited all Obelisks and found out that it is placed on square which cannot be digged.

### Save file

[Dead_Dragons and ultimate artifact.zip](https://github.com/ihhub/fheroes2/files/8960104/Dead_Dragons.and.ultimate.artifact.zip)

**Comment by oleg-derevenetz** [comment]
The funny thing is, you cannot dig this artifact in the original game too (it just looks a bit different):

https://user-images.githubusercontent.com/32623900/175128141-f5526f32-cc45-4807-a163-127c4daf2cb1.mp4

However, it really is on this tile, because the creator of the map deliberately placed it here:

![Dead-dragons](https://user-images.githubusercontent.com/32623900/175128410-2c0397be-5683-4348-bd18-34b7e7593edd.png)

Normally you should not be able to dig on the tile that has already been dug out both in original HoMM2 and in fheroes2, so it seems that the creator of the map put it here on purpose, so that it can't be dug up.

**Comment by SlavisaBelic** [comment]
Hi @oleg-derevenetz 
In the original game the hole is there. But plot says (month 2, week 2) that artifact was teleported from this place to some close location. 

I have played this map few times in original game and artifact is always close to the starting castle "Esty"

![image](https://user-images.githubusercontent.com/108020889/175233425-b6de63ec-91ac-410a-8bee-a201a3fbb0d5.png)

**Comment by oleg-derevenetz** [comment]
@SlavisaBelic

> In the original game the hole is there. But plot says (month 2, week 2) that artifact was teleported from this place to some close location.
> 
> I have played this map few times in original game and artifact is always close to the starting castle "Esty"

The ultimate artifact is always shown in the same place, because the map creator placed it here manually (see the screenshot from the map editor above). But he deliberately placed it where you can't dig it up (see the video from the original game in my first comment). Are you able to to dig it up in the original game?

**Comment by LeHerosInconnu** [comment]
Hello @SlavisaBelic and @oleg-derevenetz,

I tried with the Windows Gold 2.1 version and it is possible to dig on this location.

In original game:

https://user-images.githubusercontent.com/43583994/175241844-3fcc1ade-c9d7-4ead-93b7-203924d75216.mp4

In fheroes2:

https://user-images.githubusercontent.com/43583994/175241919-8ac6ab77-dede-4f5e-a160-e35ddda5f6a1.mp4

In the scenario editor, the radius of the Ultimate Artifact location is 21, however the Ultimate Artifact can also be found at this original location.

![Ultimate artifact radius 01](https://user-images.githubusercontent.com/43583994/175241979-317937ee-db74-49ce-8df1-ff5201c8133c.png)

**Comment by oleg-derevenetz** [comment]
> In the scenario editor, the radius of the Ultimate Artifact location is 21, however the Ultimate Artifact can also be found at this original location.

Ah yes, there is a radius. Didn't look in the properties of this artifact.

**Comment by oleg-derevenetz** [comment]
BTW it seems that this "radius" is currently ignored in fheroes2, and artifact is always placed at the tile where it was placed by the map author. We can at least try place it to the diggable tile. As for the ability to dig at the "already dug out" tile, this fix is not trivial, because fheroes2 currently looks at the terrain sprite when deciding whether it is possible to dig here, and the conditions that the original game uses in this regard are not entirely clear.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> BTW it seems that this "radius" is currently ignored in fheroes2, and artifact is always placed at the tile where it was placed by the map author. We can at least try to place it to the diggable tile. As for the ability to dig at the "already dug out" tile, this fix is not trivial, because fheroes2 currently looks at the terrain sprite when deciding whether it is possible to dig here, and the conditions that the original game uses in this regard are not entirely clear.

In the original game, the hole already dug graphic is just that, a hole already dug graphic.
One of the conditions that the hero cannot dig at a location is that this location has already been dug (with the action "Digging") by any hero.

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> In the original game, the hole already dug graphic is just that, a hole already dug graphic.
> One of the conditions that the hero cannot dig at a location is that this location has already been dug (with the action "Digging") by any hero.

Yes, I am aware of this. But currently in fheroes2 "location has already been dug" is determined based on the tile's sprite, and this is not trivial to fix, because there are many reasons why you cannot dig on the tile (in the original game you was not able to dig even on tiles containing shadows), so we still have to determine when exactly the tile may be digged and when it may not. The rules of this are still not entirely clear, so currently the somewhat simplified set of rules is applied. It is pointless to fix one specific case with one specific sprite, we need to figure out a real set of rules.
