### ISSUE TITLE
Add an option to complete battle instantly

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5626]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Sometimes players want to finish battle as soon as possible, but they don't want to run away or surrender. The only way to do this currently is to set maximum speed and initiate auto battle. Or continue playing manually.

### Describe the possible solution

I think we should implement at least hot key for now to jump to the battle outcome, as if player pressed AUTO.

**Comment by LeHerosInconnu** [comment]
Hello @@Branikolog,

What do you think about [this](https://github.com/ihhub/fheroes2/discussions/3281)? :)

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu :)
I think this is a brilliant decision, to place Auto and Instant option inside one button. :) I've recently discussed with some our members this opportunity to skip battle during the battle itself, but we haven't decided how to integrate this option into GUI. 
The only thing I'm concerning about your edited suggestion is to place new buttons near original "AUTO" button (something like drop-down menu). Heroes 2 interface never performs such button operation. I'd prefer a separate, well drawn window with nice-looking large buttons appearing in the center of the screen, like we have for Hero info for instance. This would match the overall game style more, in my opinion.
Also, I'm totally agree, that such complicated integration of few options inside one button would prevent player from accidental initiating AUTO battle. This happens quite often, actually.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Hi, @LeHerosInconnu :) I think this is a brilliant decision, to place Auto and Instant option inside one button. :) I've recently discussed with some our members this opportunity to skip battle during the battle itself, but we haven't decided how to integrate this option into GUI. The only thing I'm concerning about your edited suggestion is to place new buttons near original "AUTO" button (something like drop-down menu). Heroes 2 interface never performs such button operation. I'd prefer a separate, well drawn window with nice-looking large buttons appearing in the center of the screen, like we have for Hero info for instance. This would match the overall game style more, in my opinion. Also, I'm totally agree, that such complicated integration of few options inside one button would prevent player from accidental initiating AUTO battle. This happens quite often, actually.

I agree with a nice window with large buttons centered in the screen, this was actually my second choice. :)

Maybe it would also be possible to automatically move the mouse cursor to the "AUTO" button area in this new window?

**Comment by Branikolog** [comment]
> Maybe it would also be possible to automatically move the mouse cursor to the "AUTO" button area in this new window?

This would lead to miss clicks either. I think, Heroes players are not such type of gamers, that are lazy to move cursor a bit over the screen.)

**Comment by ihhub** [comment]
I think we ned to show a dialog upon pressing AUTO button with 2 (3) buttons / icons in it:
- AUTO battle for player on the left if applicable 
- AUTO battle for the player on the right if applicable
- AUTO complete the battle

It would also solve the problem of non-easy disabling auto mode during battle.

What do you think?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> I think we ned to show a dialog upon pressing AUTO button with 2 (3) buttons / icons in it:
> 
> * AUTO battle for player on the left if applicable
> * AUTO battle for the player on the right if applicable
> * AUTO complete the battle
> 
> It would also solve the problem of non-easy disabling auto mode during battle.
> 
> What do you think?

This is how it could be done.
A left click on the standard "AUTO" button of the original game brings up a window with several buttons.

If the combat is between two armies controlled by two human players:
When one of the human players is in control:
- "AUTO" button to activate the automatic combat mode for this player only.
- "CANCEL" button to exit the window without activating the automatic combat mode (or without changing the state of the automatic combat mode if it is already activated).

If the combat is between two armies, only one of which is controlled by a human player:
When the human player has the hand:
- "AUTO" button to activate the automatic combat mode.
- "FINISH" button to end the combat instantly (automatic combat mode without animations).
- "CANCEL" button to exit the window without activating the automatic combat mode (or without changing the state of the automatic combat mode if it is already activated).

The player should also be informed about the state of the automatic combat mode, if it is already activated (On) or not (Off) when the player opens the window (with a text, or graphically, graphically being more interesting because it doesn't require translation).

It is also possible to display the "FINISH" button when the combat is between two armies led by human players, but the combat should end instantly only if both players have pressed this button.
And this should also be well explained to the players.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu and @ihhub 
I think we shouldn't allow auto battle between two humans. The game has an ultimate and the most excited feature of gameplay: a battle between two real humans. So In my personal opinion such battles shouldn't be automated at all.
Also, if both players would press "Auto", how could each player catch a moment to stop it? Now we experience a severe problems to stop auto battle even for a single player!

>If the combat is between two armies, only one of which is controlled by a human player:
>When the human player has the hand:
>
>"AUTO" button to activate the automatic combat mode.
>"FINISH" button to end the combat instantly (automatic combat mode without animations).
>"EXIT" button to exit the window without activating the automatic combat mode (or without changing the state of the >automatic combat mode if it is already activated).

That will be OK.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog and @ihhub,

> Also, if both players would press "Auto", how could each player catch a moment to stop it? Now we experience a severe problems to stop auto battle even for a single player!

The action to make a left click on the standard "AUTO" button of the original game should have priority over all ongoing actions and stop them.

**Comment by Branikolog** [comment]
@LeHerosInconnu 
I personally prefer to stop auto battle on any single click of any button on your PC controllers. Playing on higher resolutions makes buttons too tiny, so pointing on them in a hurry could make you miss sometimes.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog and @ihhub,

> @LeHerosInconnu I personally prefer to stop auto battle on any single click of any button on your PC controllers. Playing on higher resolutions makes buttons too tiny, so pointing on them in a hurry could make you miss sometimes.

Yes, this can be extended to the whole screen and the keyboard (except the "F" keys used, for example the "F4" key to switch from full screen to windowed mode) or just the space bar.
So something like this:
When the automatic combat mode is engaged, a left click (or a click with any mouse button) anywhere on the screen or pressing any key on the keyboard (or only the space bar) stops the automatic combat mode (or brings up the new window (so that the player can change the state of the automatic combat mode, or continue in automatic combat mode if it is a miss click)).

**Comment by Branikolog** [comment]
@LeHerosInconnu 

> When the automatic combat mode is engaged, a left click (or a click with any mouse button) anywhere on the screen or pressing any key on the keyboard (or only the space bar) stops the automatic combat mode (or brings up the new window (so that the player can change the state of the automatic combat mode, or continue in automatic combat mode if it is a miss click)).

I'm not sure we need to make it so complex. Why not simply cancel auto battle without showing any dialog? (Probably we should only show text in battle log) So player can simply re-enter "auto" dialog and re-initiate auto battle once more.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog and @ihhub,

> @LeHerosInconnu
> 
> > When the automatic combat mode is engaged, a left click (or a click with any mouse button) anywhere on the screen or pressing any key on the keyboard (or only the space bar) stops the automatic combat mode (or brings up the new window (so that the player can change the state of the automatic combat mode, or continue in automatic combat mode if it is a miss click)).
> 
> I'm not sure we need to make it so complex. Why not simply cancel auto battle without showing any dialog? (Probably we should only show text in battle log) So player can simply re-enter "auto" dialog and re-initiate auto battle once more.

In fact, it works this way in the original game (the automatic combat mode can be interrupted with any mouse click or keyboard key (even "F4" key), as described (in part, not the use of the keyboard) in [this forgotten discussion](https://github.com/ihhub/fheroes2/discussions/4385). :rofl:

**Comment by Branikolog** [comment]
@LeHerosInconnu 
Nothing is forgotten. The suggestion of holding the pressed state of this button is nice. )

**Comment by oleg-derevenetz** [comment]
> I think we shouldn't allow auto battle between two humans. The game has an ultimate and the most excited feature of gameplay: a battle between two real humans. So In my personal opinion such battles shouldn't be automated at all.

Personally, I consider the possibility to enable the auto battle in PvP very useful for debugging.

> Also, if both players would press "Auto", how could each player catch a moment to stop it? Now we experience a severe problems to stop auto battle even for a single player!

Currently, each player can stop the auto battle for himself at the moment when any of his units is active (performs any action) using one the following:

1. By pressing the "AUTO" button. The auto battle will be silently turned off starting from his next unit (or even from the current unit, if he gets a good morale event);
2. By pressing the auto hotkey (usually "A"). The conditions and result are the same as in 1.
3. By pressing the escape hotkey. The conditions and result are the same as in 1, except that the process of turning off the auto battle is not silent, the "Break auto battle?" dialog will be shown.

Therefore, even now it is quite deterministic which player turns on or off the auto battle - the one whose unit is currently performing an action. There is no ambiguity in this matter. However, at high animation speeds, you can simply not have time, which can lead to confusion.

> The action to make a left click on the standard "AUTO" button of the original game should have priority over all ongoing actions and stop them.

That's how it in fact currently works.

**Comment by MoArtis** [comment]
Hello everyone!

I just wanted to add that without that option it seems currently impossible to stop a defense battle in a castle (since you cannot flee/retreat in this context).

Even if the player just want to reload the autosave to prepare their defense a bit differently, they must close the game window entirely and restart the game.

I feel like this feature is basically "I want to get out of that battle right now, whatever the outcome" and it seems that using the escape key and a confirmation could suffice in term of user experience.
It seems fitting as the Escape key can already be used to accept the outcome of battle on the adventure map.

**Comment by LeHerosInconnu** [comment]
Hello @MoArtis,

> Hello everyone!
> 
> I just wanted to add that without that option it seems currently impossible to stop a defense battle in a castle (since you cannot flee/retreat in this context).
> 
> Even if the player just want to reload the autosave to prepare their defense a bit differently, they must close the game window entirely and restart the game.
> 
> I feel like this feature is basically "I want to get out of that battle right now, whatever the outcome" and it seems that using the escape key and a confirmation could suffice in term of user experience. It seems fitting as the Escape key can already be used to accept the outcome of battle on the adventure map.

It's true that in the case of a captain or if the player does not have enough resources to retreat his hero, the player must "suffer" the combat until the end.
Which is really not practical.
And yes, keyboard shortcuts can also be set up in addition to the graphic buttons. :)
