### ISSUE TITLE
Scenario selection window, spell book purchase bug

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5633]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Sandro can't purchase a spell book due to full inventory... But this happens before game starts. :D
![image](https://user-images.githubusercontent.com/55348946/178459975-d9100d84-76fe-43ac-aaf7-571fe8cf9b35.png)
Bug occurs not each start. Just roll 5-10 times new game on this map.

### Save file

[Map_0248 bug.zip](https://github.com/ihhub/fheroes2/files/9091597/Map_0248.bug.zip)

**Comment by LeHerosInconnu** [comment]
I was unable to reproduce this bug in either single or multiplayer mode.

Version 0.9.17 5627, x64 SDL2, Windows 7

**Comment by oleg-derevenetz** [comment]
There is one random hero that already has the Magic Book in its inventory (for some reason in the second slot). I suppose it happens when for this random hero will be selected some class that should have a Magic Book (for example, Wizard). In this case the game will try to "purchase" the magic book for him and this will fail, because this hero is already has the Magic Book and he is not able to get a second one.
