### ISSUE TITLE
Adventure map, music doesn't continue after the month message

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5941]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

![image](https://user-images.githubusercontent.com/55348946/194705088-31d0df37-af75-4fbd-b3df-513a6a9f4b67.png)
To reproduce the bug you should wait a few minutes, without accepting the month message and then press OK. The game will keep silence until focus is changed or you enter a castle.

### Save file

[Month of___.zip](https://github.com/ihhub/fheroes2/files/9739081/Month.of___.zip)

**Comment by oleg-derevenetz** [comment]
The problem here is that this dialog box appears too fast, and in many cases terrain music just have not enough time to start in the background before this dialog box appears, so `MusicRestorer` has nothing to restore. But sometimes (say, in non-optimized debug builds) terrain music has time to start, and in this case everything works properly.
