### ISSUE TITLE
Trouble with sound while playing video

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#5984]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

There's a terrible noise appearing occasionally during "Roland" campaign introduction video.
Also tone is changing randomly during video playback.
The issue appeared somewhere at between 11 and 21 of september (on 0.9.19 version).

### Save file

None.

**Comment by zenseii** [comment]
The commits about audio in that timeframe are these two:
https://github.com/ihhub/fheroes2/pull/5829
https://github.com/ihhub/fheroes2/pull/5846

**Comment by oleg-derevenetz** [comment]
About a month ago we migrated the Windows build to SDL 2.24.0, and this build has the following regression:

https://github.com/libsdl-org/SDL/issues/6391

This regression sometimes causes crashes (I got a few during the video playback BTW), but also it may also cause sound distortion/noise, because, since SDL audio resampling implementation now reads outside of its buffers, it may read random garbage, and this may produce wrong resampled output.

**Comment by zenseii** [comment]
Hi, everyone.

I watched a fheroes2 video on twitch by streamer Lexiav and the issues with sound were very bad as you have described them.

There doesn't seem to have been made a PR on SDL's repo for this issue yet and since there is really no way of knowing when this will be fixed, what are our alternatives for solving this issue?

Is it possible to revert to an older SDL that did not have this regression? I'm just throwing ideas in the air here.

**Comment by ihhub** [comment]
Ideally we need to roll back to SDL version which does not have such a bug. We did not jump a lot in versions. Plus we need to make sure SDL Mixer will still work with an older SDL.

**Comment by oleg-derevenetz** [comment]
I rolled back SDL in the Windows package to the previous version (2.24.0 -> 2.0.22).

**Comment by ihhub** [comment]
Hi @Branikolog , could you please test this issue and if it's fixed in the latest build close it?

**Comment by Branikolog** [comment]
Hi, @ihhub and @oleg-derevenetz  !
The issue is gone!
Thank you for fixing it so much!
