### ISSUE TITLE
SMPEG.DLL in SDL1 have depency to missing LIBSTDC++-6.DLL

### ISSUE THREAD

**Issue by GeorgeK1ng** [ihhub/fheroes2#6007]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I have checked all files with Depency Walker and smpeg.dll have missing imports and can cause problems. I found this as real issue when testing fheroes2 under Windows XP SP3 here, but this bug have nothing to do with host as exist all Windows version and builds. This is from Windows 10
https://github.com/ihhub/fheroes2/issues/6002#issue-1415624307

![image](https://user-images.githubusercontent.com/98261225/196948489-b5bba711-f2be-4a1b-98cc-63c6f35c428c.png)

![image](https://user-images.githubusercontent.com/98261225/196948558-f68f68d9-e54d-4540-8be9-69e26e359db1.png)

If I understand correctly, here is solution how to compile it without needs of LIBSTDC++-+.DLL
https://stackoverflow.com/questions/6404636/libstdc-6-dll-not-found

### Save file

No save file

**Comment by oleg-derevenetz** [comment]
Hi @GeorgeK1ng we do not build this file ourselves, this file is taken from this pre-built archive distributed by `libsdl.org`:

https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-devel-1.2.12-VC.zip

And I don't see any reason to build it ourselves, because we are (hopefully) going to drop SDL1 support completely in the foreseeable future. Also the required library is available in the Visual C++ redistributable package, it is available for download on the MS website.

**Comment by GeorgeK1ng** [comment]
@oleg-derevenetz Why you would like to drop SDL1? SDL2 can't be launched under Windows XP and users will be limited to Vista or never hosts.

**Comment by GeorgeK1ng** [comment]
Otherwise, missing imports can be solved by these dll grabbed from internet, it's enough to place in game root.
libstdc++-6.dll
libgcc_s_dw2-1.dll
https://www.mediafire.com/file/jvoxi8zzi3pidr2/SDL1_MissingDepenciesFix.7z/file

**Comment by oleg-derevenetz** [comment]
Hi @GeorgeK1ng because development of SDL1 is frozen a long ago (for example, the latest release of SDL_mixer 1.x is from 2013), it does not support many of the features that SDL2 supports, so we have to add quirks to our code to circumvent this. The WinXP market share was less than 1% already a year ago, it is not supported by MS since 2014. We can't support end-of-life WinXP and SDL1 endlessly.

**Comment by ihhub** [comment]
I think `SMPEG` library is not used anywhere in our code. We do not play any videos using SDL.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> I think `SMPEG` library is not used anywhere in our code. We do not play any videos using SDL.

I didn't test this specially, but AFAIK SMPEG was used by SDL_mixer 1.x to play MP3 music, because it is capable to play MP3 too:

https://github.com/icculus/smpeg
