### ISSUE TITLE
Don't lowercase with Translation::StringLower() if the string comes first in a phrase.

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#6328]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Using the function `Translation::StringLower()`, there is a problem for languages that change the sentence structure from the English one, for example Russian and Belarusian, making the sentence start with a lowercased letter.

Here is an example of the typical usage of this function:
https://github.com/ihhub/fheroes2/blob/93a7615702141843420ebf1947c6e02e599bf182/src/fheroes2/army/army_bar.cpp#L307-L308

`StringLower()` does not know that the troop name `%{name}` comes first in the sentence in case a translator has chosen to do this.

I've yet to come up with a solution that works for every case of this, so I would like to ask some input.

### Describe the possible solution

The replaced string should not be lowercased when it comes first in a body of text.

**Comment by Districh-ru** [comment]
Hi, @zenseii. I made a text file from 'ru.po' file with current Russian translations , which starts from `%{`.

[Name at the first plase.zip](https://github.com/ihhub/fheroes2/files/10251602/Name.at.the.first.plase.zip)

Most `%{monster}` are first in the phrase because it is the easiest way to place a name without thinking of its gender and declension problems. :)

I could also propose not to make a function, that calls `StringReplace()`, but to make a copy of this function near it (in tools.cpp). :)
<details><summary>In example:</summary>

```cpp
#include "translations.h"

...

void StringReplaceWithLowercase( std::string & dst, const char * pred, const std::string & src ) {
    size_t pos = std::string::npos;

    while ( std::string::npos != ( pos = dst.find( pred ) ) ) {
        if ( pos == 0 ) {
        dst.replace( pos, std::strlen( pred ), src );
        }
        else {
        dst.replace( pos, std::strlen( pred ), Translation::StringLower( src ) );
        }
    }
}
```

</details>

**Comment by Districh-ru** [comment]
@zenseii, I'm currently thinking about many battlefield animation issues ... and to relax from it I'll open a PR to fix this issue. :)
