### ISSUE TITLE
[Developer tools] Create a pre-commit script + git hook

### ISSUE THREAD

**Issue by kfishster** [ihhub/fheroes2#6513]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

The repo has a good set of style checks + conventions, and I'm super grateful that it keeps it consistent throughout development. It can, however, get a bit messy when some of the checks in the PR validations flag style/copyright/tidy issues, especially when they break the build on first instance of the error. This creates additional 2-3 commits to satisfy the checks. 

Additionally, as the checks are run within Github Actions on an Ubuntu machine, it's a bit more difficult to repro the conditions/libraries locally on an Apple Silicon Mac (this is specific to my setup, so I'm definitely the minority here). 

The issue I've hit so far is that `clang-tidy` and `clang-tidy-diff` tools aren't as easily accessible (surprisingly) as they require a full llvm/clang setup + clang 14 is not compiled for arm64 by default. This part is certainly my own issue, but given that the only portion of the package that's needed for the PR validation is the `clang-tidy-diff` python script, that seems like an easier fix to pull in.

### Describe the possible solution

Although there is a `check-code-format` and `check-copyright-headers` scripts in the repo, it might be worth creating a single script that runs similar checks locally that the PR validation runs, and possibly, hooking it up as a pre-commit Git hook. This would ensure that the commit histories in a PR are cleaner, as it ensures folks run the checks locally before pushing their changes.

It might also be helpful to adopt a more platform-agnostic tidy/code checker that could be run on all machines. Clang is already platform agnostic, but making one more change to pull in the clang-diff logic as a python script instead of a package manager dependency might help here.

### Additional info

Again, for the `clang-tidy` complains, I fully admit it's specific to the Mac M1 case, and I certainly don't expect to change things due to this small scenario, just wanted to point it out in case other folks hit this as well.

**Comment by oleg-derevenetz** [comment]
> This part is certainly my own issue, but given that the only portion of the package that's needed for the PR validation is the `clang-tidy-diff` python script, that seems like an easier fix to pull in.

`clang-tidy-diff` is nothing without `clang-tidy` itself. `clang-tidy-diff` just runs the `clang-tidy` for the pieces of code that were changed (using the `-line-filter=` argument). It's the `clang-tidy` that performs all the heavy lifting. And I'm not going to rewrite it in Python :) Not to mention that it is based on LLVM anyway, because it's actually a kind of compiler.

> Although there is a check-code-format and check-copyright-headers scripts in the repo, it might be worth creating a single script that runs similar checks locally that the PR validation runs, and possibly, hooking it up as a pre-commit Git hook.

You can just run these scripts from a hook, there is nothing that prevents you from doing this. But if you want to impose a similar approach on everyone, then you need to offer a cross-platform solution, because many Windows developers don't even have Python installed (for example, there is no Python on my Windows machine at all). This will immediately and unnecessarily raise the threshold for entering development.

**Comment by ihhub** [comment]
Hi @kfishster ,

@oleg-derevenetz is correct about this. Even in big corporations you have to follow certain installation steps in order to achieve your goal for multiple OSes. I am talking like Python installation and configuration on Windows which might be a pain for some people. The idea which is used in this project is to minimize and ease the installation work for developers.

As an alternative solution you might create such bash scripts and add documentation for their installation as a section (tentatively) called "Optional development tools" if there is a need to do this.

**Comment by kfishster** [comment]
I would also agree that enforcing the pre-commit hook is likely overkill, and definitely agree that there should be the least possible friction for contributions. The reason I mentioned Python is primarily because it is a good option for a cross-platform scripting engine that allows all platforms/OSes to be on the same page.

I also agree that the initial proposal is very ambitious and the right solution here is, as @ihhub, you mentioned, an optional script that can emulate some of the validations happening within the CI process. Unfortunately, given the `clang-tidy` dependencies, and constant need to keep the CI yml + optional validation script in sync, it might be difficult for someone on a different OS setup to reproduce the exact errors that might come up in the CI.

Ideally, there would be a single validation script that runs both in the CI and is cross-plat enough that it can be run locally on any developer's machine. This would come with it's own optional set of dependencies.

**Comment by oleg-derevenetz** [comment]
> Ideally, there would be a single validation script that runs both in the CI and is cross-plat enough that it can be run locally on any developer's machine. This would come with it's own optional set of dependencies.

Performing basic checks (such as checking the copyright date) is a relatively simple task and does not require any dependencies other than Python. But with more advanced checks situation is different - they require something that is aware of C++ syntax, which is complex and should be understood in its entirety, including templates, `std` library and advanced features from latest C++ standards if necessary. In other words, advanced checks should use some compiler backend. In general, currently there is no alternative to Clang/LLVM in this regard. You won't be able to get by with a simple Python script.

**Comment by ihhub** [comment]
I am closing this issue as the proposed idea is developer dependent. For instance, Visual Studio users on Windows have no easy way to install all tools. There is no need to install them as our GitHub Action pipeline will tell what's wrong.
