### ISSUE TITLE
Setting Hero Speed to Jump leads to full CPU core usage on Adventure map

### ISSUE THREAD

**Issue by Districh-ru** [ihhub/fheroes2#6534]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When you set Hero Speed to Jump the CPU core maximally loads on adventure map.
Opening any dialog (by right mouse click) returns the CPU load to normal.
Setting any Hero speed other than Jump also returns the CPU load to normal.

### Save file

1. Launch fheroes2.
2. Open the process explorer in OS and locate the fheroes2process.
3. Start a new game or load a saved game.
4. In System Options set Hero Speed to Jump.
5. Close the System Options dialog (return to the Adventure map) and check the CPU usage of fheroes2 process.

### Additional info

When setting the "Jump" speed `CURRENT_HERO_DELAY` is set to `0` in `game_delays.cpp`. Changing this delay to 1 ( `delay.setDelay( 1 );` ) makes the game to run normally without high CPU load.
Maybe the issue is somewhere in the loop `while ( res == fheroes2::GameMode::CANCEL )` in `game_startgame.cpp`.

**Comment by ihhub** [comment]
Hi @Districh-ru , this is critical issue and the fix is obvious. It shouldn't be 0. Setting to 1 is the correct solution. Explanation:
```cpp
    while ( res == fheroes2::GameMode::CANCEL ) {
        if ( !le.HandleEvents( Game::isDelayNeeded( delayTypes ), true ) ) {
```
In this code we are checking whether the delay is needed. If the value of the delay is always 0 then delay is not needed and no sleep call will be done within **HandleEvents()** method. This means that this method is going to be called tremendous amount of times (infinite loop). Setting the value to 1 fixes the problem since sleep function will be called.

Please go ahead and create a pull request for this issue.
