### ISSUE TITLE
Discontinue Visual Studio 2017 project files

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#6578]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

I think we reached the point where nobody is using Visual Studio 2017. I asked in Discord whether anyone is still using it. If not then we will proceed with removing it. However, it is not required right now as no harm to be done if we keep it.

### Describe the possible solution

Just remove VS 2017 files.

**Comment by oleg-derevenetz** [comment]
I use it when I'm on Windows PC :) MSVC 2019 supports newer language features, but MSVC 2017 is still enough to build fheroes2 and it's more lightweight than more recent versions, so I use it.

**Comment by ihhub** [comment]
Sure. That's why I marked it as low priority and we can even close it if you wish.

**Comment by kitovyj** [comment]
I got this error after downloading the code and building from sratch in the up-to-date vs2017 community. So, maybe it's not possible to build the project in its present state in vs2017 anyway.

1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xmemory0(881): error C2280: '`anonymous-namespace'::KeyboardButton::KeyboardButton(const `anonymous-namespace'::KeyboardButton &)': attempting to reference a deleted function (compiling source file src\fheroes2\gui\ui_keyboard.cpp)
1>d:\games\heroes2\fheroes2\src\fheroes2\gui\ui_keyboard.cpp(188): note: see declaration of '`anonymous-namespace'::KeyboardButton::KeyboardButton' (compiling source file src\fheroes2\gui\ui_keyboard.cpp)
1>d:\games\heroes2\fheroes2\src\fheroes2\gui\ui_keyboard.cpp(188): note: '`anonymous-namespace'::KeyboardButton::KeyboardButton(const `anonymous-namespace'::KeyboardButton &)': function was explicitly deleted
...

**Comment by oleg-derevenetz** [comment]
Yeah, didn't tried to use MSVC 2017 for a while... It seems that the `std::vector` implementation from MSVC 2017 sometimes requires its elements to be copy-constructible, but buttons in their current form cannot be copy-constructible because `ButtonBase` has a member of type `std::unique_ptr`, which is naturally isn't copy-constructible by itself. We can either drop the MSVC 2017 support or implement the proper copy operation for `ButtonBase`.

**Comment by ihhub** [comment]
I actually faced the same issue while working on the related change. This can appear on VS2019 as well.

**Comment by ihhub** [comment]
I will try to avoid this issue by fixing the code. Dropping VS2017 for such a particular case doesn't solve the problem.

**Comment by oleg-derevenetz** [comment]
I have no idea why `std::vector` wants the copy constructor. On reallocation only move constructor is needed, and if we don't use `push_back` and friends, but only `emplace`-like functions, then there should be no need for copy constructors.

**Comment by kitovyj** [comment]
> 

I've investigated the issue a bit. The thing is that the generation of the explicitly defaulted move constructor can implicitly fail (pain in the neck!).

Simple test shows that KeyboardButton is not movable:
 
		const char L = letterRows[0][0];
		KeyboardButton kb( std::string( 1, L ), defaultButtonWidth, isEvilInterface, [L]( KeyboardRenderer & renderer ) {
                    renderer.appendCharacter( L );
                    return DialogAction::AddLetter;
                } );

		KeyboardButton kb1(std::move(kb)); // fails

The reason for that is the std:function member:

std::function<DialogAction( KeyboardRenderer & )> action;

Its removal (together with its usage) makes the code compile.
Even adding an innocent member std::function<void()> foo; to the declaration brings the error back.

It seems that the cause is that the move constructor of std::function in <functional> is declared without "noexcept". 

Noexcept move constructor can not use "except" move constructors of its members. Interestingly std::vector move constructor is declared as "noexcept". Did they just forget "noexcept" for std::function or there is a reason for that? I wonder, what is the situation in vs2019 - I can't check it now due to account problems.  BTW, removing "noexcept" in the definition of the KeyboardButton mover also fixes the issue.

**Comment by oleg-derevenetz** [comment]
> I wonder, what is the situation in vs2019 - I can't check it now due to account problems.

With MSVC 2019 everything is OK, it is used by our CI. Modern clang and gcc are also OK.
