### ISSUE TITLE
Wrong description on some other terrain objects

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#660]
This type of tree is often signed as an object, which is located close to that tree.
![Objects2](https://user-images.githubusercontent.com/55348946/83138540-9d9c8880-a0f3-11ea-8154-57e579188ce4.jpg)
![Objects](https://user-images.githubusercontent.com/55348946/83138544-9f664c00-a0f3-11ea-8855-cfe521098d54.jpg)

**Comment by idshibanov** [comment]
This is actually OG behavior, caused by original map editor and how objects are stored in MP2 files. Examples from the editor:

![image](https://user-images.githubusercontent.com/1373638/86135020-486be200-bab8-11ea-9936-1f860dcc92b3.png)
![image](https://user-images.githubusercontent.com/1373638/86135035-4dc92c80-bab8-11ea-9db0-14c61e1d5328.png)

@Branikolog Look at the actual size of Tree of knowledge in the game. We can try to find a workaround but it might create more issues. How to determine which of the **green** "top" tiles are a tree and which are not?

**Comment by ihhub** [comment]
This issue is beyond the scope of 1.0 release and will be covered as a part of the upcoming Editor.

**Comment by nogov** [comment]
Hi, @Branikolog!

I've faced the same issue with a Witch's Hut on Broken Alliance [16, 44]:
![step1](https://user-images.githubusercontent.com/10126377/211785419-e5ac8640-0be0-496c-b54b-6b03505a95a3.png)
![step2](https://user-images.githubusercontent.com/10126377/211785474-0cbae115-ead2-4679-a5c5-699c2a5512ce.png)

More to that, a hero can step on this tile but can't dig in it. Does it deserve a 'logic' bug label?

**Comment by Branikolog** [comment]
Hi, @nogov 
Unfortunately, the original game works completely the same. We cannot dig on that tile, which looks empty, but has wrong description. In the future editor, I believe, we'd avoid this problem. Not sure, this could be fixed within the current map format.
I hope, fheroes2 engine doesn't place UA there... I will check it later.

**Comment by ihhub** [comment]
I am closing this issue as this is a problem of the original Editor. Such a problem would not occur in our Editor.
