### ISSUE TITLE
Combat screen, combat crash (1.0.1 6678)

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#6715]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Crash during a combat initiated by an AI hero during the AI's turn.
Reproducible by doing the same actions.

In fheroes2:

https://user-images.githubusercontent.com/43583994/221373836-c1a4f406-4c84-432d-9f26-19694abd009f.mp4

### Save file

Here is the save file:
[AI attack combat crash 01.zip](https://github.com/ihhub/fheroes2/files/10831994/AI.attack.combat.crash.01.zip)

**Comment by Districh-ru** [comment]
Hello @oleg-derevenetz!
The assertion for checking the wide creature one step back triggered. But for some reason the last move of reversing the Hydras is missing: We have only 45->33->22 (without the 4th step ->23).
![изображение](https://user-images.githubusercontent.com/113276641/221376913-ab48d81e-3984-41b1-9edf-c95ed350730b.png)
![изображение](https://user-images.githubusercontent.com/113276641/221376915-974f6b67-3a43-4405-801a-c79d362514bd.png)

When I try to replicate such move in Battle only mode I get the correct `path`:
![изображение](https://user-images.githubusercontent.com/113276641/221377149-bed9d5f9-db13-4425-a223-9b6d4e3557a7.png)
![изображение](https://user-images.githubusercontent.com/113276641/221377172-a532cc34-a9e1-4e45-9385-5de81dae57af.png)

**Comment by oleg-derevenetz** [comment]
> but should the path be generated without the turning back for wide creature back move?

This is not quite the full path in this case. What AI want is to take the position at cells [11, 12], but Hydras are not so fast, so the path is sort of "cropped" to the last reachable cell, namely cell 22. This is fine usually, because there is auto-rotation logic in the `Battle::Arena::ApplyActionMove()`, but this is not good for that assertion. We could turn that assertion into the additional check to ensure that the last movement is in fact the turn back.

**Comment by Districh-ru** [comment]
> We could turn that assertion into the additional check to ensure that the last movement is in fact the turn back.
Sure, I'll do it tomorrow.
BTW if we have an auto-rotation logic maybe we don't need to generate the last rotation move (22->23 for Hydras be human control).

**Comment by oleg-derevenetz** [comment]
@Districh-ru

> BTW if we have an auto-rotation logic maybe we don't need to generate the last rotation move (22->23 for Hydras be human control).

Well, what the pathfinder actually operates with is not individual cells, but positions (head+tail pairs). It maintains the graph of positions (see #6479 for details). In case of wide units the final position will be [23, 22], so the pathfinder will still add the last rotation move, because that's the target position requested, and not the [22, 23].
