### ISSUE TITLE
Adventure map, pathfinding doesn't update after revealing the fog on visiting "magellan's map" object

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#6733]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

If I come to magellan's map, **cancel the first dialog**, press "spacebar" and buy map I cannot target any place from the revealed area until I make any movement.

https://user-images.githubusercontent.com/55348946/221848305-a97ca17f-fe22-4d68-9326-2a3a936a09b2.mp4

### Save file

[Magellan issue.zip](https://github.com/ihhub/fheroes2/files/10849977/Magellan.issue.zip)

**Comment by oleg-derevenetz** [comment]
Yeah, the adventure map pathfinder's cache do not track the visibility of map tiles for now, only the hero's parameters.

BTW most likely this may happen in other similar circumstances, for example, when a hero takes a Treasure Chest on a neighboring tile (without movement), gets a level up and chooses the Scouting skill - his scouting area will be increased, but he most likely will not be able to reach the newly discovered tiles immediately, but only after any movement (or any other hero's movement).

The problem here is that tracking of such kind is relatively expensive, especially on large maps. We need to think about how to implement it better.

**Comment by Branikolog** [comment]
@oleg-derevenetz The curious thing is that this happens only on revisiting magellan's map. On the first visit everything works correctly.

**Comment by oleg-derevenetz** [comment]
> The curious thing is that this happens only on revisiting magellan's map. On the first visit everything works correctly.

That's because on the first visit the hero previously moved and his map position was changed. If you re-visiting the object, the hero's position will not change and pathfinder will not recalculate its cache.
