### ISSUE TITLE
Crash when starting a map that contains heroes with non-default experience value

### ISSUE THREAD

**Issue by oleg-derevenetz** [ihhub/fheroes2#6765]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

How to reproduce:

1. Build the game in debug mode (with `WITH_DEBUG` defined);
2. Run the game and start the attached map (or any other map that contains heroes with non-default experience, e.g. "Arrax the Jerk");
3. Observe the crash inside the `Heroes::Scoute()` method during the hero level up.

### Save file

[!BOATTST.zip](https://github.com/ihhub/fheroes2/files/10893226/BOATTST.zip)

**Comment by oleg-derevenetz** [comment]
Hi @Districh-ru could you please take a look?

**Comment by Districh-ru** [comment]
Hi @oleg-derevenetz, I'll check it in the evening.

**Comment by Districh-ru** [comment]
This crash causes because the level up on map load is done to heroes before they are assigned to a player (they have NONE color). And if during level up the Scouting skill is leveled the `Scoute()` method is called:
https://github.com/ihhub/fheroes2/blob/2c0af4c9d583a679bd5c167fe91c8e396c5885cc/src/fheroes2/heroes/heroes.cpp#L1437-L1441
I've recently added a check if the player is under AI-auto-control. So the check results in a crash as it tries to get data from unexisted player with NONE color.
I also think that we shold skip `Scoute()` and `ScoutRadar()` for this case as revealin the fog for the NONE player waste CPU and may give unpredictible results (I don't know where is the fog data of NONE player is used).
So I'll add a condition to the line 1438: `&& GetColor() != Color::NONE `
