### ISSUE TITLE
Elves' arrow starting position is shifted

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#687]
Arrow start position is shifted down:
![Arrow2](https://user-images.githubusercontent.com/55348946/83352923-a7262a80-a357-11ea-915f-973422ac6cec.jpg)
![Arrow3](https://user-images.githubusercontent.com/55348946/83353000-329fbb80-a358-11ea-8cbd-5257633a6bf7.jpg)

**Comment by idshibanov** [comment]
This is more limitation of an Elf sprite (not leaning down) rather than position shift. Original Heroes2, first frame when arrow appears, captured from Dosbox:
![image](https://user-images.githubusercontent.com/1373638/83373849-d2c90500-a397-11ea-9609-38d7ff633214.png)

Same story. We can create a special case and manually adjust the offset for it, but it's an improvement rather than a bug.

**Comment by Branikolog** [comment]
> Same story. We can create a special case and manually adjust the offset for it, but it's an improvement rather than a bug.

I'm completely agreed with you. 
Original game has tons of problems as our version do. :)
