### ISSUE TITLE
Adventure map, AI is obsessed with lighthouse

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7081]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Defensive AI continues capturing the same lighthouse.

https://user-images.githubusercontent.com/55348946/235298231-53e20b6f-a0b3-453c-b640-d664c280ab28.mp4

### Save file

[AI loves ligthouses.zip](https://github.com/ihhub/fheroes2/files/11358943/AI.loves.ligthouses.zip)

**Comment by oleg-derevenetz** [comment]
What is happening here is that green hero tries to capture the upper lighthouse (which is not captured yet) and `AIPathfinder` paves the path through the lower (already captured) lighthouse, because it can (it's perfectly legal). But when hero reaches the lower lighthouse, AI planner decides that castle has the priority over that upper lighthouse and hero goes back to the castle.

**Comment by Branikolog** [comment]
So, naturally, this issue is clone of #7082, where AI keeps returning to his castle each time he decides to walk away.
