### ISSUE TITLE
Bug in Bulgarian Translated buttons

### ISSUE THREAD

**Issue by Effektus** [ihhub/fheroes2#7087]
I found this bug!

![image](https://user-images.githubusercontent.com/12934196/235373045-d874e282-a875-44c5-bf04-a6acc47a4f77.png)

_Originally posted by @Effektus in https://github.com/ihhub/fheroes2/issues/7066#issuecomment-1529123856_

**Comment by Districh-ru** [comment]
Hi @Effektus.
Thanks for pointing out this issue.
It is partially fixed in #7056. But the main problem is that this text does not fit the button: Currently the text system when the only word extends the maximum width renders the letters that agree the maximum width plus one extra letter which is outside the maximum width. All other letters will be on the next line. And if it is the last letter of the word we have an empty line.
I'll try to fix this in the next days.

I think we need to expand this button a little. As Bulgarian and Russian inhalations will not wit it.
What do you think @zenseii?

**Comment by Effektus** [comment]
Yes this is one of solutions the other solution is smaller letters maybe. Do it what is possible. Thanks for fast answer!

**Comment by Districh-ru** [comment]
@zenseii, if you need help, please tell.
