### ISSUE TITLE
Improve AI hero behavior when handling Daemon Cave

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#7098]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

AI heroes always fight when visiting Daemon Cave but somehow they consider to visit it only when there is an artifact. A hero receives only 2500 Gold after a battle so it is not particularly correct behavior for AI heroes.

### Describe the possible solution

Expand the logic for AI heroes.

**Comment by oleg-derevenetz** [comment]
> but somehow they consider to visit it only when there is an artifact

This is not quite true. The condition looks like this:

```cpp
if ( doesTileContainValuableItems( tile ) && getDaemonCaveBonusType( tile ) != Maps::DaemonCaveCaptureBonus::PAY_2500_GOLD ) {
```

so it checks whether the cave has not been visited yet, as well as whether the demon will demand a ransom if you refuse to fight him. Currently AI always choose to fight, so the second condition is redundant. We can do so that AI will choose to fight only if bonus type is `PAY_2500_GOLD` (i.e. demon will demand a ransom in case of refusal to fight), but this will in fact a cheating, because human player doesn't know the bonus type in advance, so AI will have an unfair advantage.

**Comment by ihhub** [comment]
In this case we should at least remove the second condition as AI always choses to fight.
