### ISSUE TITLE
Adventure map, to re-visit stone liths AI choses too distant and not optimal cell

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7140]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Sometimes to re-visit stone liths AI hero choses a cell to step and return, which requires him to waste not 1 movement, but 2 or more. Sometimes he starts to walk around some abject and then returns back, wasting all his movement points.

https://user-images.githubusercontent.com/55348946/236819476-18333faf-374b-4341-9ff4-4cd5405561fd.mov

One of red heroes here (0:14) choses a cell right above stone liths.

### Save file

[Stuck in Liths.zip](https://github.com/ihhub/fheroes2/files/11420934/Stuck.in.Liths.zip)

**Comment by Branikolog** [comment]
@oleg-derevenetz 
In some cases AI hero is certainly makes just 1 step and then jumps back (supposedly as he didn't find any interest in the location). In other situations he makes two steps and then it's waiting till other heroes use stone liths. But I'm pretty sure, I saw situations, when AI hero appeared, made 2 steps and then immediately returns back into teleporter.
If you're sure in the save file above everything is ok, I can close the issue. :+1:

**Comment by oleg-derevenetz** [comment]
> But I'm pretty sure, I saw situations, when AI hero appeared, made 2 steps and then immediately returns back into teleporter.

I tried to mitigate this issue in #7143. You see, this "deadlock resolution" logic currently choose one nearby accessible tile by random, but it doesn't check whether this tile is **_directly_** accessible by a hero. For example, the tile located directly above the Stone Liths is undoubtedly a "nearby" tile in regard to the tile with Stone Liths and may be "accessible" (if nothing blocks the way), but it is not **_directly_** accessible, because hero will need to perform 2 movements instead of one. I added the appropriate check for candidate tiles, now this should happen much less often (only if, after moving to the next cell, AI cannot find a task for the heroes, then new moves are possible). Please take a look when you have time.
