### ISSUE TITLE
Adventure map, there is a drop in volume when an interaction window is opened while the audio setting "Music Type" is set to "External" and there is no "MUSIC" folder present

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#7181]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there is a drop in volume when an interaction window is opened while the audio setting "Music Type" is set to "External" and there is no "MUSIC" folder present.

In fheroes2:
Activate the sound of the videos.

https://github.com/ihhub/fheroes2/assets/43583994/e8121bac-af5b-45c4-9744-5406f72ce917

https://github.com/ihhub/fheroes2/assets/43583994/fe359fd8-660d-4e19-8a73-96684573f57f

### Save file

Here is the save file:
[Sound down window out 01.zip](https://github.com/ihhub/fheroes2/files/11472066/Sound.down.window.out.01.zip)

### Additional info

Related issue: https://github.com/ihhub/fheroes2/issues/7182.

**Comment by oleg-derevenetz** [comment]
That's because if music type is set to External, then game tries to play the "musical" effect and temporarily set the music volume to equal to the audio effects volume, but since there is in fact no music track for the corresponding "musical" effect, this track fails to start, and the usual background music continues to play with the volume of sound effects until the corresponding dialog box closes.
