### ISSUE TITLE
AI heroes refuse to attack enemy castles

### ISSUE THREAD

**Issue by kitovyj** [ihhub/fheroes2#7195]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

3 saved snapshots from the same game.  The first case: the red hero (Zom) takes a long way via Dimention Door towards green castle but then, standing in front of it, steps away. Maybe there is some rationale behind - the hero tries to avoid being trapped in the castle or tries to leave the area reachable by enemy heroes. The next save shows a similar scenario but looks more like a bug - Zom jumps towards a castle but then avoids taking it but goes towards enemy heroes. The third case is the strangest - the green hero avoids taking the last enemy castle despite miserable garrison. Note also the suicidal subsequent action of the red hero.

### Save file

[3savedgames.zip](https://github.com/ihhub/fheroes2/files/11502267/3savedgames.zip)

**Comment by oleg-derevenetz** [comment]
The first two cases are not observed anymore, heroes behave differently now, as well as in the third case, there are no more any suicidal actions of the red hero. In the third case, Gwenneth decides not to attack red hero Zom in the castle because of overwhelming Zom's superiority in magic - his magic stats and a set of spells gives him more "strength points" that the whole Gwenneth's army (it's hard to say how justified this is, but so far it is). Gwenneth herself with her 3 spell power and 20 spell points a weak opponent in this sense, so she prefers to not attack and wait for Vesper to finish the job.

**Comment by kitovyj** [comment]
> The first two cases are not observed anymore, heroes behave differently now, as well as in the third case, there are no more any suicidal actions of the red hero. In the third case, Gwenneth decides not to attack red hero Zom in the castle because of overwhelming Zom's superiority in magic - his magic stats and a set of spells gives him more "strength points" than the whole Gwenneth's army (it's hard to say how justified this is, but so far it is). Gwenneth herself with her 3 spell power and 20 spell points a weak opponent in this sense, so she prefers to not attack and wait for Vesper to finish the job.

Yes, thank you, I checked, AI behaviour much more natural now. I think we should close the issue due to #7500 and other improvements.
