### ISSUE TITLE
The game hangs after the end of a move

### ISSUE THREAD

**Issue by alexanderadline** [ihhub/fheroes2#7213]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

In the last mission for Roland, when I finish a turn, the game suddenly hangs.
Save file attached.

Tested on both Intel and Silicon Macs, version 1.0.4

### Save file

[AUTOSAVE.savc.zip](https://github.com/ihhub/fheroes2/files/11525162/AUTOSAVE.savc.zip)

**Comment by oleg-derevenetz** [comment]
Hi @alexanderadline I was not able to reproduce this issue on the latest snapshot, neither on Windows nor on macOS:

https://github.com/ihhub/fheroes2/assets/32623900/460a09a8-e5e4-435a-b04d-60bb36c8e3ed

Before opening an issue, it is recommended to check that the problem is reproducible on the latest snapshot. Did you tried the latest snapshot?
