### ISSUE TITLE
Incorrect Russian translations

### ISSUE THREAD

**Issue by MapmakerLich** [ihhub/fheroes2#7285]
### Your question

I get it that Buka's work back in 90s wasn't perfect, but some of re-translations are just plain wrong.

For example, we have 2 objects: one gives +1 sp to hero permanently and another gives a secondary skill. In RU version they are named the same - "Хижина ведьмы". Also, the changes of faction's names are strange. Warlock is an "evil" faction, but now they have the part about that omitted - they are using old Wizard's name while actually they are supposed to be evil counterpart for Sorceress faction. Ogres now became "maneaters" for strange reason. 

This list can go on and on and on, but please - consider reverting some changes to Buka's original (I hope that you didn't ended up with 7Wolf translation as base for RU TL)

**Comment by ihhub** [comment]
Hi @Branikolog and @Districh-ru , could you please take a look at this proposal?

**Comment by Districh-ru** [comment]
Hi, @ihhub, I'll address this issue a little closer to the release along with the translation of new phrases.

**Comment by ihhub** [comment]
@Districh-ru , thank you!

**Comment by Branikolog** [comment]
Hi, @ihhub 

All statements of @MapmakerLich are valid:
We should rename ogres into ogres.
Witch Doctor's hut in official Russian localization has the same name to witch hut. I think we should introduce different translation not to confuse players with same names for different objects.
Faction names differences come from the time we had an issue with long names in scenario selection window. That's why there is a mess with names, as we tried to translate faction name with shorter name. Now we have an ability to divide word into two strings so we can return official faction names: "Чародей" and "Чернокнижник" to Wizard and Warlock respectively. 

I haven't played Buka version much, so there could be some more issues which I haven't noticed. It would be nice if @MapmakerLich would kindly continue the list of differences.
