### ISSUE TITLE
Castle siege, towers near the bridge are not destroyable

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7478]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In the OG in some cases (like using earthquake spell) towers near bridge could be destroyed too:
![image](https://github.com/ihhub/fheroes2/assets/55348946/c0b8c92f-fe1a-42ad-b9d7-6e8f08a218af)

While in fheroes2 they are always untouched:
![image](https://github.com/ihhub/fheroes2/assets/55348946/5107872e-0a0e-499e-b0dd-1c85395ab4e0)

### Describe the possible solution

I propose to show damaged towers near the bridge once it was destroyed.

**Comment by ihhub** [comment]
Hi @Branikolog , could you please tell other cases when the 2 towers can be destroyed?

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog and @ihhub,

Would this apply only to the Earthquake spell, or also to catapult shots?

For the Earthquake spell, the towers near the drawbridge could also be hit, as is the case in the original game.

As for the catapult, since it's just a graphical effect, I don't have anything against it, but I think the towers shouldn't be hit systematically.
For example, it could be:
- 5% chance of hitting both towers
- 10% chance of hitting the top tower
- 10% chance of hitting the bottom tower
- 75% chance of hitting neither tower
