### ISSUE TITLE
AI goes ouf of a castle and returns back having done nothing.

### ISSUE THREAD

**Issue by kitovyj** [ihhub/fheroes2#7545]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The red AI hero Atlas goes ouf of a castle and returns back having done nothing. I don't remember if approaching an enemy castle can reveal details about the army strength there, so the red could just change his mind. However, he does that several times. I could be some event triggered there also.

### Save file

[goes-and-returns.zip](https://github.com/ihhub/fheroes2/files/12327102/goes-and-returns.zip)

**Comment by kitovyj** [comment]
Similar situation but maybe different cause in this saved game also: Natasha approaches neutral town and then turns back without visible reason (an event?).
[goes-to-and-back.zip](https://github.com/ihhub/fheroes2/files/12327109/goes-to-and-back.zip)

**Comment by oleg-derevenetz** [comment]
> I could be some event triggered there also.

Yes, it's mostly due to the event. The event stopped the hero and forced him to reconsider his thoughts.

> Similar situation but maybe different cause in this saved game also: Natasha approaches neutral town and then turns back without visible reason (an event?).

In this case Natasha just scouting the fog of war. She never intended to attack the castle because she is too weak - she won't be able to handle 13 Orcs, 14 Goblins and 2 Ogres in the garrison with her Sprites and Dwarves.

**Comment by kitovyj** [comment]
> > I could be some event triggered there also.
> 
> Yes, it's mostly due to the event. The event stopped the hero and forced him to reconsider his thoughts.
> 
> > Similar situation but maybe different cause in this saved game also: Natasha approaches neutral town and then turns back without visible reason (an event?).
> 
> In this case Natasha just scouting the fog of war. She never intended to attack the castle because she is too weak - she won't be able to handle 13 Orcs, 14 Goblins and 2 Ogres in the garrison with her Sprites and Dwarves.

Thank for the clarification abput Natasha! Regarding the event, it is not one time event, yes? The hero did that loop several times and keeps doing it again. I wonder, what is so important in the event that forces him back to his castle.

**Comment by oleg-derevenetz** [comment]
> Regarding the event, it is not one time event, yes? The hero did that loop several times and keeps doing it again. I wonder, what is so important in the event that forces him back to his castle.

There is nothing important. Before #7549, AI always stopped on an event, even if it wasn't able to handle it, because it was human-only event. It was unnoticeable from the player's point of view, but each stop forces the AI to reevaluate the situation taking into account its new position. For some reason, AI decided that the previous castle is now more attractive to visit. Here it is also necessary to take into account that AI, being in some castle, does not consider it as a target for visiting (because it is already in it), and when leaving it begins to consider it as a potential target. This is the current mechanics.

**Comment by kitovyj** [comment]
Thanks, then I close the issue.

**Comment by kitovyj** [comment]
Closed with #7549
