### ISSUE TITLE
A path arrow is rendered over AI controlled human hero

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#7558]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

A path arrow is rendered over a human hero which is controlled by AI. Also notice that the part of the path is not rendered sometimes.

This is a low priority task as AI mode is available only for developers.

### Save file

https://github.com/ihhub/fheroes2/assets/19829520/328a9cf3-9858-4852-a996-b3d4ed0c754e

**Comment by oleg-derevenetz** [comment]
According to my observations, the part of the path is not rendered in two cases:

1. Hero is "stopping" because of New targets found during the fog discovery;
2. Hero is just started his move, in this case first arrow in the path is not rendered (it's the proper behavior as well).

Unlike human-controlled heroes, AI heroes never just stand with already paved path. If this is taken into account, then the drawing of the path works quite logically for them, because it is actually not designed for such heroes. I doubt that we need to "fix" this somehow, because it's just a developer mode for debug.
