### ISSUE TITLE
Meeting screen, morale and luck sprites, sprites of the hero on the right side are not correctly centered horizontally related to the portrait frame and the screen frame

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#7660]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the sprites of the hero on the right side are not correctly centered horizontally related to the portrait frame and the screen frame.
Sprites should be shifted horizontally 4 pixels to the right.

In fheroes2:

![Moral luck icons not centered right part 01](https://github.com/ihhub/fheroes2/assets/43583994/c5cd2fd0-ed1e-48a5-96d1-09e872fed1ea)

Enlarge the image.

![Moral luck icons not centered right part recadré 01](https://github.com/ihhub/fheroes2/assets/43583994/af7b9700-13fe-4a27-91df-25c0993bdfe1)

### Save file

Not needed.

### Additional info

Related closed issue: https://github.com/ihhub/fheroes2/issues/1722.

**Comment by dood-apo** [comment]
I think this is intentional. Please note, that the shadow (4px wide) of both hero frames is directed to the left. In these circumstances the current positioning looks visually appealing. The pixel perfect centering while disregarding the shadow looks worse in my opinion, as shown on the picture. @zenseii I propose to close this one.

![image](https://github.com/ihhub/fheroes2/assets/84446398/a037e56f-d046-4c27-8778-0b69fa91364c)

**Comment by dood-apo** [comment]
Hi @zenseii , 

> Usually we pixel align things in the engine and disregard the shadows.

Since that's the case, I've submitted a PR for consistency sake.
