### ISSUE TITLE
Update Copyright to year xxxx to present.

### ISSUE THREAD

**Issue by Mr-Bajs** [ihhub/fheroes2#7759]
Not a big issue but, instead of having to update the copyright claims every year in several files it would be more convenient to just have the

Copyright (c) 20xx-present

I think several open source projects are going with this route.

**Comment by oleg-derevenetz** [comment]
> I think several open source projects are going with this route.

Of course, I am not a lawyer, but as far as I know, specifying the specific year of the last code change may be important because in most jurisdictions copyright protection is not eternal and expires in a few decades. GNU recommends to specify at least a range, and even better - individual years:

https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html

I don't think that "- present" is legal if you don't make regular changes to the code.

**Comment by ihhub** [comment]
As @oleg-derevenetz mentioned we have automated checks for this so there is no issue of doing this. Plus I've never seen a proper project stating present as date.

I'm closing this issue as no action is required.

**Comment by oleg-derevenetz** [comment]
> I think Godot Engine and Microsofts vscode atleast have the year to current, in their copyright, but then again they are having the MIT licence and not GPL

As for MS vscode, I don't see any years at all in their headers:

https://github.com/microsoft/vscode/blob/main/src/vs/loader.js

"Copyright (c) Microsoft Corporation. All rights reserved.", that's all.

**Comment by oleg-derevenetz** [comment]
While I can enforce copyright date check for PO files, I don't want to burden our translators by this so far.
