### ISSUE TITLE
AI is sitting at the teleport from the start of the game

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#7794]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

AI got to this teleport and is standing here for at least 2 moths.
He could go pick up these chest or scout, or even go back to the teleport, but he is just standing:
![AI is just idle](https://github.com/ihhub/fheroes2/assets/145407420/1c3595ff-1e1c-467a-bff0-c2b6733c1e44)

As far as  I know, there is no problem to go to the side opposite the monsters, I tested it:

https://github.com/ihhub/fheroes2/assets/145407420/cc2f8404-bc15-45be-b01c-1a9aaf91a8e4

[AI is scared to go up.zip](https://github.com/ihhub/fheroes2/files/12695767/AI.is.scared.to.go.up.zip)

### Describe the possible solution

Improve AI pathfinding, seems like he need to go left or right, but monsters will kill him, but idea of going up is not included in AI.

**Comment by oleg-derevenetz** [comment]
> Improve AI pathfinding, seems like he need to go left or right, but monsters will kill him, but idea of going up is not included in AI.

You can't go up "right through" a Stone Liths object.

> As far as I know, there is no problem to go to the side opposite the monsters, I tested it

That's because in your test you don't go "right through" a Stone Liths object. But in reality you just can't do that:

![screenshot](https://github.com/ihhub/fheroes2/assets/32623900/8dc2a659-0bba-4181-ab7d-063ab70c9155)

**Comment by Branikolog** [comment]
In this particular case AI is simply frightened by guarding monsters, but he cannot do any move without triggering the battle. 
Actually, in the original game behaviour was completely the same: any hero (even controlled by a human) could appear here and stay for eternity. It can even break some maps, where player couldn't reach this area because of AI hero standing on the exit. I think the main issue is to teach AI using spacebar to re-visit stone liths and go away. 
I propose to close this thread, as after fixing https://github.com/ihhub/fheroes2/issues/7139 there would be no such problems.

**Comment by fheroes2bugs** [comment]
Agree about teach AI using spacebar, but also looks like a bug in original game, that for moving up you need 1 step right or left. Authors of heroes2 hate up? There is no logic of that behavior.

**Comment by ihhub** [comment]
Closing this issue in favor of #7139.

**Comment by Branikolog** [comment]
@fheroes2bugs 

> Agree about teach AI using spacebar, but also looks like a bug in original game, that for moving up you need 1 step right or left. Authors of heroes2 hate up? There is no logic of that behavior.

I believe that's a mistake of map makers. You can easily move guarding creatures a little away from stone liths so any hero can came out and then return back.
