### ISSUE TITLE
Battle: AI is moving units with no profit

### ISSUE THREAD

**Issue by fheroes2bugs** [ihhub/fheroes2#7804]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In this situation boar attack centaurs, and gargoyles attack boars. But they are not standing at one place, they are moving for no reason.

https://github.com/ihhub/fheroes2/assets/145407420/db5f7bd1-dd73-43c9-8966-326dda71a2e5

### Describe the possible solution

If there is no profit, then not to waste time and not to move unit.

### Additional info

[AI loses and I am not.zip](https://github.com/ihhub/fheroes2/files/12705443/AI.loses.and.I.am.not.zip)

**Comment by ihhub** [comment]
The AI moved boars is a better strategy since less your units can attack the boar (if any). I don't see a problem with the AI moving creatures, unless I am missing something and this affects on the outcome of the battle.

For now I am closing this issue.
@fheroes2bugs  if you think that I am wrong please reopen the issue as explain in more details why we should change the current behavior.
