### ISSUE TITLE
Combat, "safe" AI move doesn't consider obstacles on a battlefield

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#7972]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

https://github.com/ihhub/fheroes2/assets/55348946/f11d2290-a840-4956-9667-dfb9eb13d8ed

As you can see on the video, wolves being afraid of enormous stacks of boars prefer to take a "safe" position, even in those areas, where boars couldn't reach because of obstacles.

I've also met similar issue, when during siege attacking champions ignore castle gates and make just 1 step forwards, instead of coming close to walls, to be able to step in a moat if some walls were destroyed.

### Save file

[Broken_Alliance master.zip](https://github.com/ihhub/fheroes2/files/13060336/Broken_Alliance.master.zip)

**Comment by oleg-derevenetz** [comment]
This is because now, when assessing the threat, it is not the distance from the battle pathfinder's point of view that is taken into account, but the straight line distance. The first one is certainly more accurate, but its calculation takes much longer, because in this case we will need to rebuild the pathfinder's database for every enemy unit, while calculation of the straight line distance is just a few arithmetic operations.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
I see. But because of current logic in this particular case wolves are not able to reach halfings on the second round, which allows player to win the battle with minimum losses.

If I'm not mistaken, sometimes AI places his troops so far, while my fastest unit was not able to move at all, because it was stuck behind defending troops in front of the unit.

So I hope, a nice compromise solution could be found some day for this problem.
