### ISSUE TITLE
"Hypnotize" spell wrong description

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#811]
![Hypno3 desc](https://user-images.githubusercontent.com/55348946/84630948-4ff68d00-aef5-11ea-8e41-10621f421fe8.jpg)
"Hypnotize" spell is active till hypnotized unit hits anybody. If it just moves or skips turn, the spell will last according to spellpower of hero.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog 

Since I'm already dealing with this spell (#3027) - as far as I see in the code, this spell in fheroes2 it works as you described, but is this really the right way to work for it? As far as I can see, everywhere in the manuals said that hypnotize should affect an enemy for just 1 round:

https://mightandmagic.fandom.com/wiki/Magic_(H2)#Level_Five_Spells
http://tartarus.rpgclassics.com/hmm2/spells.php

And I think that this description is taken directly from OG. Is this a known bug in OG (in the sense that in OG the behavior of this spell doesn't match the manual)?

**Comment by Branikolog** [comment]
Hello, @oleg-derevenetz !
That sounds like a topic for a discussion. So here can be two solutions. Either the description doesn't match the spell mechanics or spell does not work correctly....
I think for now we should stick to original behaviour of the spell. As changing of spell mechanics can confuse the OG players. Probably in future addon we would rework the operation of this spell. But for now it should work the same to original. So the description should coinside with the spell operation. 
I mean the description should tell a player, that spell will last till the target hits anybody.

**Comment by oleg-derevenetz** [comment]
@Branikolog Then we can just remove words "for one combat round" from the spell's description. AFAIK other mind control spells (like berserker or blind or paralyze) do not mention that they will be active until the unit attack or attacked, this behavior is implied for all mind control spells.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Could be.
But being not a native speaker of english I can't advise the best wording for game descriptions. ;)
