### ISSUE TITLE
Teach AI to garrison slower troops in the castle at the end of turn

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#8207]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Currently when the AI ends the turn and it has a hero visiting a castle, it will not garrison any troops, which means that the next day their movement points will be based on a potentially slow troop in that army. Instead, if it would garrison these troops, it would get a single-turn movement points boost that can be good for many reasons, like having a greater chance to reach nearby objects and get back to the castle in one turn, among many other things.

Additionally, since by default you get more detailed information about troops in a hero's army than a castle's garrison, not garrisoning is suboptimal. One exception being the times when you own 2 thieves guilds. Therefore, garrisoning troops would then improve this by hiding what troops the AI has to the human player.

This is an example of the hero visiting the castle and you can see that they have garrisoned 0 troops, keeping the very slow Golems in their army. The best way here would be to only keep the very fast boars in their army.

<img width="103" alt="image" src="https://github.com/ihhub/fheroes2/assets/12501091/75a886e5-7cfb-417e-9702-445d2d1ac160">
<img width="112" alt="image" src="https://github.com/ihhub/fheroes2/assets/12501091/f9d39f80-9f95-4bf2-8609-8ca4c953a00d">

### Describe the possible solution

Teach the AI to garrison troops by leaving only the fastest troops in its army, whether that is a single troop type or several. The AI will need to garrison troops in the corresponding castle slot they would have wanted the troops to be in their army in case they get attacked.

I suggest to avoid making a very complex logic for it, since even just a simple one would bring big benefits. For example, there can be special cases where you could optimize more, like if your castle has ultra fast troops that you don't intend to keep in your army the next day, but you know that you are in no threat to be attacked, so you move them to your army just to get the movement points, and replace them with desirable troops the next day. However, I suggest not diving into such cases - They are few, and just doing the basic variant of this optimization will be much better than the average heroes 2 player from my experience (I've never seen a streamer do or be aware of this trick).

Ideally, the AI should keep the one, or the several troops, with the highest speed in its army, and "move up" in the garrison the troops that are slower, starting with the slowest one in case the castle has slots filled with creatures already.

Note that this should only be done at the end of the player turn for every hero the AI currently has in a castle, not for every visit to a castle. I suppose it would even be beneficial for heroes that are permanently stationed in a castle for the reason of concealing its actual army.

### Additional info

Relates to this https://github.com/ihhub/fheroes2/issues/6755

**Comment by fheroes2bugs** [comment]
Agree with the issue, just wanted to add an example.

In this video, after I lose the battle, red computer decides to hire 3 new heroes, but he has no creatures to hire, so he is travelling with starting army... There is no reason to travel with halfings - you will be beaten anyway (this is month 4)... With only sprites, boars and halfings you can't kill neutral creatues. Even on 1 week you kill only few level-1 creatures.

https://github.com/ihhub/fheroes2/assets/145407420/2df77347-be40-4c63-b680-389f5378ffa9


It would be better to leave slow forces at the town or give them to some "main hero", so those secondary heroes would get more movement points. In this case, every new hero could travel with 1 boar, all the sprites and battle dwarfes could go to "main hero" .
Version: 1.0.11
Save:
[suicide.zip](https://github.com/ihhub/fheroes2/files/13796787/suicide.zip)

**Comment by oleg-derevenetz** [comment]
Hi @zenseii

> I've never seen a streamer do or be aware of this trick

I don't know about HoMM2 streamers, but pro tournament HoMM3 players use this all the time, as well as a number of other techniques - for example, during combat, forcing powerful, but relatively slow units to go back and forth, luring them with the help of fast flying stacks, usually consisting of 1 unit. BTW this works just fine in fheroes2 too, because AI-controlled units here also prefer to attack a relatively weak, but reachable on the current turn target, rather than a more dangerous, but distant one. Consider:

https://github.com/ihhub/fheroes2/assets/32623900/6827df91-5e48-4cf7-bdf2-fb2c936c2d52

That's why in #8206 I say that AI vs AI battles are not indicative at all for pre-evaluating results AI vs human battles.

**Comment by oleg-derevenetz** [comment]
I should note that HoMM3 battle AI is also not very sophisticated and plays by well-known rules that can be easily abused. HoMM3 tournament maps/templates are made in such a way that one human player does not have to fight with the another human player all the time - often there is only one PvP "final" battle per game at all. Mainly, a human player fights against AI, clearing the way to objects on the map to boost his heroes, collect most of valuable artifacts and assemble the largest possible army. The one who is better able to abuse battles against AI (pro HoMM3 players know all the tricks) and who is the fastest to boost his power (using hero chains to quickly deliver reinforcements and so on) will win.

**Comment by oleg-derevenetz** [comment]
> I never really liked the well-known exploit of making the walkers chase single fairies around the battlefield, because it feels too cheap.

BTW recently HotA added a new faction (Fabric) and a new campaign for this faction, and I suspect that this campaign just cannot be completed without using various tricks. The difference in losses with and without using tricks can be enormous. Here is an example video:

https://github.com/ihhub/fheroes2/assets/32623900/fcfbaddb-30e8-4906-a22c-70b067d8e2fd

I suspect that HotA developers are not making efforts to radically improve AI behavior so that such campaigns remain "passable". And I think that pro players will be very upset if the opportunity to use such tricks disappears :)

**Comment by oleg-derevenetz** [comment]
> BTW a little exploit-ish I found when testing the first kiting improvement PR is this tactic of using the Ammo Cart with a few very fast shooters to take out huge amounts of slow walkers

But if both elves and ogres were controlled by human players (even the very skilled ones), nothing would have changed, and the ogres would have lost. I don't see what the "exploit" here is :) According to my understanding, "exploit" is when you use the imperfection of AI algorithms to win where a human player would have done something differently, but in this case with the same armies and artifacts a human player would have done nothing, and the result would have been the same.

> NOTE: Don't auto-resolve this one with such high numbers because it will take a looooong time for it to finish the battle. My PC took a few minutes... Retreat if you need to end the battle.

That's because of debug build :) In release build it takes about 15 seconds:

https://github.com/ihhub/fheroes2/assets/32623900/bfbe1dcd-32b1-46e8-8fd6-91909d626182
