### ISSUE TITLE
Incorrect scaling when Windows DPI is set to other than 100%

### ISSUE THREAD

**Issue by zenseii** [ihhub/fheroes2#8209]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

On Windows 11 (I haven't tested others), I have set the DPI setting to 150% and this leads to fheroes2 creating a window which is 50% larger than the selected resolution in the app. This leads to non-integer scaled pixels even in the integer scaled resolutions (i.e. 640x480 (2x) ).

In fact on my Intel iGPU PC there is no resolution available that gives integer scaled pixels with the DPI set to 150%, which is the default DPI set by the OS for this PC, and there is no simple way of adding custom resolutions.

This is true for both Full Screen and Windowed mode.

I have Software Cursor set to on.

Looking around I see that others have noticed the same issue with SDL/Windows, perhaps this one suggesting to use `SDL_GetDisplayDPI()` could be a solution:
https://www.reddit.com/r/sdl/comments/115p1ft/comment/j937j67/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

I'm aware that this is not directly a fheroes2 bug, but it might be worth investigating to make the user experience better.

### Save file

No save file needed.

### Additional info

This SDL repo issue talks about what approach to use for SDL3:
https://github.com/libsdl-org/SDL/issues/7134

This is a discussion related to SDL scaling and how MacOS uses points not pixels and potential problems with that, I believe we have no such issues right now for MacOS as none have reported it.
https://discourse.libsdl.org/t/high-dpi-mode/34411/2

Slightly related to https://github.com/ihhub/fheroes2/issues/5250 and the connected PRs

**Comment by Branikolog** [comment]
Hi, @zenseii 
I have similar problem on my Win8 laptop: running a low-res application on default appears to be scaled ~1.5x (game window appears to be larger, than 640x480). Because of this I cannot get pixel perfect image on the screen. But there's an option to switch off such scaling in compatibility settings of app. prosperities. So each time I install new fheroes2 application I have to switch of scaling.
Maybe this could help you...

**Comment by oleg-derevenetz** [comment]
In fact, it is _correct_ scaling :) You asked for a 150% scale, and you got it, which is exactly what should be happening.

> Another thing I noticed is that this is only a problem in Release builds, and not debug builds for some reason.

In debug builds scaling is not applied at all: if you have 2 monitors, then one is set to scale 150%, and the other is not, then when you transfer the window of the binary running under the debugger between these two monitors, you will notice that even the size of the window title will not change. I suppose that's because the debug version is not exactly "windows" app, it is actually "console" app, but with a window.
