### ISSUE TITLE
Debian

### ISSUE THREAD

**Issue by a-detiste** [ihhub/fheroes2#8248]
fheroes2 has been added to Debian (only unstable release for now) and will be in Ubuntu 24.04.

There users can use `game-data-packager` to prepare the non free assets.

**Comment by oleg-derevenetz** [comment]
Hi @undef21 please accept my congratulations!

**Comment by undef21** [comment]
Hi @oleg-derevenetz, it was team work)

**Comment by oleg-derevenetz** [comment]
Hi @undef21 should we update our installation instructions somehow?

**Comment by undef21** [comment]
Hello @oleg-derevenetz 

For Debian-based systems (Debian >= 12, Ubuntu >= 23.04) we could add info about packing OG assets with `game-data-packager` instead of using `extract_homm2_resources.sh`.

Also for using system-wide installed assets we could build `fheroes2_ubuntu_arch.zip` with `FHEROES2_DATA=/usr/share/games/fheroes2` by default.

When debian packages will be in the testing repository we could add something like:
```
On Debian >= 13, Ubuntu >= 2404 you can install engine from repository, but if you want the latest version, follow this instruction.
```
