### ISSUE TITLE
Innoextract needed for fheroes2-extract-resources script on macOS

### ISSUE THREAD

**Issue by pyltime** [ihhub/fheroes2#8425]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

When following the Homebrew instructions [here](https://ihhub.github.io/fheroes2/INSTALL.html#macos-resources) to extract the files from the installer using the `fheroes2-extract-resources` script, it fails with the following error:

> innoextract was not found in your system. Unable to extract the installer package. Installation aborted.

This can be fixed by first installing `innoextract` via Homebrew: 
`brew install innoextract`

It would be great if the `fheroes2-extract-resources` script could be updated to install `innoextract` if not already available; failing that, it would help to include the instructions to install `innoextract` in the installation documentation.

### Save file

Save file is not relevant as the issue is with the installation process.

**Comment by oleg-derevenetz** [comment]
> It would be great if the `fheroes2-extract-resources` script could be updated to install `innoextract` if not already available

This will definitely not be done on our part, because this is a universal script used on both macOS and various Linux flavors, and this script is not aware which package manager should be used to install applications on this particular OS (MacPorts? Homebrew? apt? portage? etc, etc). All it can do is tell what exactly is missing in the hope that the user will be able to install the appropriate package.

This is not a bug. Reclassifying this as a request for improvement.

**Comment by oleg-derevenetz** [comment]
In fact, this problem should be redirected to the maintainers of fheroes2 package for Homebrew: they can just add `innoextract` as a dependency for this package, and that's all.

**Comment by oleg-derevenetz** [comment]
Closed due to https://github.com/Homebrew/homebrew-core/pull/163402.
