### ISSUE TITLE
Roland Campaign - 10th mission. Start with a smaller number of troops than in the original version of the game.

### ISSUE THREAD

**Issue by TLCD17** [ihhub/fheroes2#8727]
In the 10th mission, we start with 5 black dragons under the command of Roland if we have not completed the 8th mission, but then without the artifact from the 8th mission. If we obtained the artifact in mission 8, we start with this artifact, but with a small amount of troops - 2 giants under the command of Roland. On YouTube and in speedruns HOMM 2 it is noticeable that Roland starts with 16 or 19 black dragons in the tenth mission. This amount should be taken so that the last mission can be completed. The tactics of the last mission of the Roland campaign are simple (I found it on the Internet): "The last day to get Roland on the ship is the first day of the second week, so by then you need to build the best possible army. And in the first week, the player cannot attack Archibald."
I suggest that the 10th mission be easier to complete and I will suggest that Roland has a dozen or so black dragons to start with.
I personally attempted this mission several times with 5 BDs without the artifact or with giants and the artifact, but I was unable to complete it in any way.

**Comment by oleg-derevenetz** [comment]
> In the 10th mission, we start with 5 black dragons under the command of Roland if we have not completed the 8th mission

That's not quite true. If you have not completed the 8th mission (and chose the mission 7 instead), in mission 10 you will get the troops which the "initial" hero of the mission 7 will have at its completion (after the final battle). This is literally written in the description of the 7th mission:

![roland7](https://github.com/ihhub/fheroes2/assets/32623900/19897416-7ef8-430d-9b74-23f9c302dfbb)

As for the option when you choose to find a Crown (mission 8 instead of mission 7), in this case in the original game Roland will get 2 giants in the mission 10:

https://github.com/ihhub/fheroes2/assets/32623900/eda8685d-cd25-4654-b9d6-7990012f4160

No army will be carried over to the mission 10.

**Comment by ihhub** [comment]
We aren't going to change the logic nor missions for the original campaign.

@oleg-derevenetz explained everything in finest details. Closing this issue as nothing we need to do.
