### ISSUE TITLE
Licensing of ./files/data/resurrection.h2d clarification

### ISSUE THREAD

**Issue by lemenkov** [ihhub/fheroes2#9267]
### Your question

I'd like to clarify the status of the only binary file shipped with fheroes2 engine, namely ```./files/data/resurrection.h2d```. Since it was added with PR #3828 I guess it is licensed under the same terms as the rest of that particular contribution (GPLv2 or later) but I'd like to double check it.

@ihhub am I correct?

**Comment by oleg-derevenetz** [comment]
Hi @lemenkov technically, this is not the only binary file shipped :) There are also PNG/ICO images, etc. In fact, `resurrection.h2d` also applies exactly to this series, because it's the set of images (or, if you like, an archive of images in a special format) that can be managed by the `h2dmgr` tool provided in this repo. In terms of the GPL license, it is also no different from the rest of the images, but let's wait for an answer from @ihhub for complete clarity.

**Comment by ihhub** [comment]
Hi @lemenkov ,

@oleg-derevenetz is correct: all non-source code files created within this repository are under the same GPL license. We do not ship any files from the original game together with the engine. All third-party libraries have the same or even lighter licensing.

**Comment by ihhub** [comment]
I am closing this issue as the answer for the question was given.

**Comment by lemenkov** [comment]
@ihhub thanks for clarification!
