### ISSUE TITLE
Compilation of engine component using gcc leaves all objects files in the same directory

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#9324]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

While making changes in engine component of the project you can notice that object files are located in the same directory as the source files:
![image](https://github.com/user-attachments/assets/7a064678-de40-4fad-9a33-af1d7e1dbd80)

This is true using makefile approach.

### Describe the possible solution

We should place object files in a separate place not to mess with source files.

**Comment by oleg-derevenetz** [comment]
> While making changes in engine component of the project you can notice that object files are located in the same directory as the source files:

Well, that's usually the case with projects based on plain `make`. BTW, the same is observed with `libsmacker` and tools. On the contrary, I would say that the fact that `fheroes2` object files are stored in the `dist` directory is somewhat unusual :) This is not usually done, for instance, because object files in different directories may have the same names. If it is necessary to have the object files separately, then it is better to use CMake (`cmake -B ...`) for this (BTW, CMake reproduces the project directory structure inside its `CMakeFiles/target.dir` directory to solve the potential issue with matching names).
