### ISSUE TITLE
No rule to make target '../engine/libengine.a'

### ISSUE THREAD

**Issue by Stiivi** [ihhub/fheroes2#9331]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

When building 2804353ac3520742bcc04f6644b2965101de3768 on MacOS the `make` command fails with:

```
make[2]: *** No rule to make target '../engine/libengine.a', needed by 'fheroes2'.  Stop.
```

Did fresh pull and `make clean`.

Some possible pointers: the `libengine.a` is in `src/engine` not in `src/dist/engine`, same for `libsmacker.a`.

### Save file

(no save file needed)

**Comment by oleg-derevenetz** [comment]
Well, it builds just fine both on our CI and on my macOS for instance. Regarding object files and libs in `src` and not in `src/dist`, these are leftovers from the previous build logic and should be removed manually, because there are no Makefiles anymore that will remove them automatically. I have an impression that this issue is related to `VPATH` logic and that the proper manual clean-up should fix it.

**Comment by Stiivi** [comment]
Refreshing `src/` (removing it recursively and checking it out again) helped. Cheers.
