### ISSUE TITLE
Issue with cursor positioning at the end of the line

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#9345]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I found several issues with cursor positioning while clicking near the end of the line:

https://github.com/user-attachments/assets/c9368ad2-e70e-487b-8f8b-7ba8df17c5a3

https://github.com/user-attachments/assets/dd5ca62a-31ed-40bc-b3db-d042681c54a8

For tests I've used the latest version (after merging #9319 )

### Save file

None.

**Comment by ihhub** [comment]
Hi @Districh-ru , could you please take a look at this issue?

**Comment by Districh-ru** [comment]
Hi, @Branikolog, could you please upload a map with this test text if you have saved it because I'm not able to quickly reproduce the second bug. :(

https://github.com/user-attachments/assets/44da91bc-d74f-45d8-ae23-47ecccf7cfa7


The first bug is not certainly a bug - you click on a character to place a cursor on it's place and it is placed right before this character. And in such long line there is no empty place to consider it as the area after the line end. In my video there is only one pixel at the line end and when you click it the cursor places really at the end of the line.
Maybe we should expand the click area in this dialog in future...
In future we could update the logic to place cursor after the character if you press on the right half of it, but it is more tricky. :)

**Comment by Branikolog** [comment]
Hello, @Districh-ru ! 
Here's the map, where I could reproduce both issues. I believe the first issue occurs for the lines with a certain length. I've noticed, that because of blinking cursor one symbol jumps back and forth between lines, depending on the presence of the cursor. Sometimes I can select press the end of the line, but sometimes it's impossible, depending on the overall symbols width. I think, we should shorten the line a bit, so the last symbol does not jump on the next line.

[Map 01.zip](https://github.com/user-attachments/files/18195353/Map.01.zip)
The text is in the events field.
![image](https://github.com/user-attachments/assets/cf092940-5ee9-4725-bc0b-067e75be37dd)
(the issues occur on both long lines in the reverse order: Cyrillic symbols - second issue, Latin symbols - first issue.)
