### ISSUE TITLE
Text should be centered in a pop up windows in adventure options menu

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#970]
Text in all pop up windows after right click over all buttons should be shifted down.
![Pop up](https://user-images.githubusercontent.com/55348946/86574418-7ea8d600-bf7e-11ea-9842-4784d0310c81.jpg)

**Comment by a1exsh** [comment]
This is already fixed in the `HEAD`:
![image](https://user-images.githubusercontent.com/489601/134463571-7c84a23f-b486-49d3-b6b1-207282d50f8f.png)

**Comment by Branikolog** [comment]
Hi, @a1exsh.
2 of 4 info texts are not centered in pop up windows:
![image](https://user-images.githubusercontent.com/55348946/145679691-1367729c-5f36-46ca-9143-bcdac2cfa5be.png)
![image](https://user-images.githubusercontent.com/55348946/145679696-ee6b8059-f1a7-4b36-a360-aa55b6956500.png)

**Comment by a1exsh** [comment]
> 2 of 4 info texts are not centered in pop up windows

Could you please be more specific? I don't see any issues.

**Comment by Branikolog** [comment]
@a1exsh 
Text has not equal space between upper and bottom border of the window.
![text alignment](https://user-images.githubusercontent.com/55348946/145680080-9fc5c34c-2167-4b68-9660-a03234e1c0d0.png)

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog and @a1exsh,

This window cannot have a precise size in pixels, because the window frame decoration has to have a fixed size.
So, this problem is present in all fheroes2 windows. :)
I think that all windows should have the same layout to achieve visual consistency in the game.
I made a proposal in this sense here: https://github.com/ihhub/fheroes2/issues/1260.

**Comment by ihhub** [comment]
I am closing this issue as we are not going to fix it.
